### ISSUE TITLE
bug: query with conditional aggregate is incorrect when duplicate column names are present

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#5655] opened 2023-03-02 17:01 UTC
### What happened?

Hello!

I'm trying to perform an as-of merge (on a backend that doesn't support it directly). Given tables like:

```python
>>> left = ibis.table([("on", "int"), ("by", "string")], "left")
>>> left
UnboundTable: left
  on int64
  by string
>>> right = ibis.table([("on", "int"), ("by", "string"), ("val", "float")], "right")
>>> right
UnboundTable: right
  on  int64
  by  string
  val float64
```

I wrote logic to perform my desired operation (based on https://ibis-project.org/ibis-for-sql-programmers/#conditional-aggregates):

```python
stat = right[(right.by == left.by) & (right.on <= left.on)]["on"].max()
merged = left.join(right, how="left", predicates=left.by == right.by)[right.on == stat]
ibis.show_sql(merged)
```

Resulting in the following output:

```sql
SELECT
  t0.on_x,
  t0.by_x,
  t0.on_y,
  t0.by_y,
  t0.val
FROM (
  SELECT
    t1."on" AS on_x,
    t1.by AS by_x,
    t2."on" AS on_y,
    t2.by AS by_y,
    t2.val AS val
  FROM "left" AS t1
  LEFT OUTER JOIN "right" AS t2
    ON t1.by = t2.by
) AS t0, "right" AS t1
WHERE
  t1."on" = (
    SELECT
      MAX(t1."on") AS "Max(on)"
    FROM "right" AS t1
    WHERE
      t1.by = (
        SELECT
          anon_1.by
        FROM (
          SELECT
            t2."on" AS "on",
            t2.by AS by
          FROM "left" AS t2
        ) AS anon_1
      )
      AND t1."on" <= (
        SELECT
          anon_2."on"
        FROM (
          SELECT
            t2."on" AS "on",
            t2.by AS by
          FROM "left" AS t2
        ) AS anon_2
      )
  )
```

My main concern above is that the `"left"` in the subqueries doesn't seem to reference/use the same alias as outside.

What I wanted was something more like what I would get by renaming some columns first:

```python
right = ibis.table([("_on", "int"), ("_by", "string"), ("val", "float")], "right")
stat = right[(right._by == left.by) & (right._on <= left.on)]["_on"].max()
merged = left.join(right, how="left", predicates=left.by == right._by)[right._on == stat]
ibis.show_sql(merged)
```

Resulting in the following output:

```sql
SELECT
  t0."on",
  t0.by,
  t1._on,
  t1._by,
  t1.val
FROM "left" AS t0
LEFT OUTER JOIN "right" AS t1
  ON t0.by = t1._by
WHERE
  t1._on = (
    SELECT
      MAX(t1._on) AS "Max(_on)"
    FROM "right" AS t1
    WHERE
      t1._by = t0.by AND t1._on <= t0."on"
  )
```

I did want to verify whether these were somehow equivalent, but I don't think so. For example:

```python
>>> con = ibis.duckdb.connect()
>>> con.raw_sql("CALL dbgen(sf=0.001)")
>>> orders = con.table("orders")
>>> left = orders.select(
...     orders.o_orderstatus.name("by"),
...     (orders.o_orderdate.year() + orders.o_orderdate.month() / 12).name("on"),
... )
>>> left
┏━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ by      ┃ on          ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━┩
│ !string │ float64     │
├─────────┼─────────────┤
│ O       │ 1996.083333 │
│ O       │ 1997.000000 │
│ F       │ 1993.833333 │
│ O       │ 1995.833333 │
│ F       │ 1994.583333 │
│ F       │ 1992.166667 │
│ O       │ 1996.083333 │
│ O       │ 1995.583333 │
│ F       │ 1993.833333 │
│ O       │ 1998.583333 │
│ …       │           … │
└─────────┴─────────────┘
>>> right = orders.group_by(
...     [orders.o_orderstatus.name("by"), orders.o_orderdate.year().name("on")]
... ).aggregate(val=orders.o_totalprice.max())
>>> right
┏━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ by      ┃ on    ┃ val             ┃
┡━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ !string │ int32 │ !decimal(15, 2) │
├─────────┼───────┼─────────────────┤
│ O       │  1996 │       237947.61 │
│ F       │  1993 │       230949.45 │
│ O       │  1995 │       245976.74 │
│ F       │  1994 │       249900.42 │
│ F       │  1992 │       240457.56 │
│ O       │  1998 │       263411.29 │
│ P       │  1995 │       245388.06 │
│ O       │  1997 │       258779.02 │
│ F       │  1995 │       228136.49 │
└─────────┴───────┴─────────────────┘
>>> import pyarrow.parquet as pq
>>> pq.write_table(left.to_pyarrow(), "left.parquet")
>>> pq.write_table(right.to_pyarrow(), "right.parquet")
>>> left = con.read_parquet("left.parquet")
>>> right = con.read_parquet("right.parquet")
>>> stat = right[(right.by == left.by) & (right.on <= left.on)]["on"].max()
>>> merged = left.join(right, how="left", predicates=left.by == right.by)[right.on == stat]
>>> ibis.show_sql(merged)
SELECT
  t0.by_x,
  t0.on_x,
  t0.by_y,
  t0.on_y,
  t0.val
FROM (
  SELECT
    t1.by AS by_x,
    t1."on" AS on_x,
    t2.by AS by_y,
    t2."on" AS on_y,
    t2.val AS val
  FROM ibis_read_parquet_1 AS t1
  LEFT OUTER JOIN ibis_read_parquet_2 AS t2
    ON t1.by = t2.by
) AS t0, ibis_read_parquet_2
WHERE
  ibis_read_parquet_2."on" = (
    SELECT
      MAX(t1."on") AS "Max(on)"
    FROM ibis_read_parquet_2 AS t1
    WHERE
      t1.by = (
        SELECT
          ibis_read_parquet_1.by
        FROM ibis_read_parquet_1
      )
      AND t1."on" <= (
        SELECT
          ibis_read_parquet_1."on"
        FROM ibis_read_parquet_1
      )
  )
>>> merged.count
5865
>>> right = right.select(right.by.name("_by"), right.on.name("_on"), right.val)
>>> stat = right[(right._by == left.by) & (right._on <= left.on)]["_on"].max()
>>> merged = left.join(right, how="left", predicates=left.by == right._by)[right._on == stat]
>>> ibis.show_sql(merged)
WITH t0 AS (
  SELECT
    t2.by AS _by,
    t2."on" AS _on,
    t2.val AS val
  FROM ibis_read_parquet_2 AS t2
)
SELECT
  t1.by,
  t1."on",
  t0._by,
  t0._on,
  t0.val
FROM ibis_read_parquet_1 AS t1
LEFT OUTER JOIN t0
  ON t1.by = t0._by
WHERE
  t0._on = (
    SELECT
      MAX(t0._on) AS "Max(_on)"
    FROM t0
    WHERE
      t0._by = t1.by AND t0._on <= t1."on"
  )
>>> merged.count()
1500
```

1500 is correct, given the original `orders` table had 1500 entries.

Sorry for the circuitous example; I'm bad at Ibis. I needed to reset the expression trees, so I wrote and read back from Parquet. FYI if you don't reset the expression trees, `ibis.show_sql(merged)` errors out, even though `merged` is generated:

```python
>>> ibis.show_sql(merged)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/ibis/expr/sql.py", line 324, in show_sql
    print(to_sql(expr, dialect=dialect), file=file)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/ibis/expr/sql.py", line 392, in to_sql
    (pretty,) = sg.transpile(sql, read=read, write=write, pretty=True)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/__init__.py", line 177, in transpile
    for expression in parse(sql, read, error_level=error_level)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/__init__.py", line 65, in parse
    return dialect.parse(sql, **opts)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 707, in parse
    return self._parse(
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 770, in _parse
    expressions.append(parse_method(self))
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 906, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1498, in _parse_select
    this = self._parse_statement()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 906, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1541, in _parse_select
    from_ = self._parse_from()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1678, in _parse_from
    exp.From, comments=self._prev_comments, expressions=self._parse_csv(self._parse_table)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3316, in _parse_csv
    parse_result = parse_method()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1908, in _parse_table
    subquery = self._parse_select(table=True)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1547, in _parse_select
    this = self._parse_table() if table else self._parse_select(nested=True)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1908, in _parse_table
    subquery = self._parse_select(table=True)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1541, in _parse_select
    from_ = self._parse_from()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1678, in _parse_from
    exp.From, comments=self._prev_comments, expressions=self._parse_csv(self._parse_table)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3316, in _parse_csv
    parse_result = parse_method()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1908, in _parse_table
    subquery = self._parse_select(table=True)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1547, in _parse_select
    this = self._parse_table() if table else self._parse_select(nested=True)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1908, in _parse_table
    subquery = self._parse_select(table=True)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 1526, in _parse_select
    expressions = self._parse_csv(self._parse_expression)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3323, in _parse_csv
    parse_result = parse_method()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2226, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2229, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3332, in _parse_tokens
    this = parse_method()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2232, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3332, in _parse_tokens
    this = parse_method()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2235, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3332, in _parse_tokens
    this = parse_method()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2238, in _parse_range
    this = self._parse_bitwise()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2303, in _parse_bitwise
    this = self._parse_term()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2326, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3339, in _parse_tokens
    expression=parse_method(),
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2329, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 3339, in _parse_tokens
    expression=parse_method(),
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2334, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2342, in _parse_type
    this = self._parse_column()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2478, in _parse_column
    this = self._parse_field()
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2568, in _parse_field
    return self._parse_primary() or self._parse_function() or self._parse_id_var(any_token)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2598, in _parse_function
    this = parser(self)
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 600, in <lambda>
    "CAST": lambda self: self._parse_cast(self.STRICT_CAST),
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 2989, in _parse_cast
    self.raise_error("Expected TYPE after CAST")
  File "/opt/miniconda3/envs/ibis-issue/lib/python3.10/site-packages/sqlglot/parser.py", line 816, in raise_error
    raise error
sqlglot.errors.ParseError: Expected TYPE after CAST. Line 6, Col: 176.
   AS SMALLINT) + CAST(EXTRACT(month FROM t4.o_orderdate) AS SMALLINT) / CAST(CAST(12 AS SMALLINT) AS DOUBLE_PRECISION) AS "on" 
FROM orders AS t4) AS t2 LEFT OUTER JOIN t0 ON t2.by = t0.by) AS t1, t0 
WHERE t0."on" = 
```

Thanks for taking a look!

### What version of ibis are you using?

4.1.0

### What backend(s) are you using, if any?

DuckDB (but I actually care about the SQL generation, not the backend)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment] 2023-03-06 15:08
@deepyaman Thanks for the report!

I am able to reproduce this.

I this is related to other issues we have around join UX. In short, we haven't yet made it easy to deal with overlapping column names. Stay tuned though because we're working on it!

**Comment by cpcloud** [comment] 2024-01-27 15:00
Fixed in `the-epic-split`.

**Closed by cpcloud** 2024-01-27 15:00 UTC
Labels: bug, chained joins
