### ISSUE TITLE
 HiveServer2Error: Error while compiling statement: FAILED: SemanticException [Error 10025]: Line 1:7 Expression not in GROUP BY key 'day'

### ISSUE THREAD

**Issue by z7ye** [ibis-project/ibis#3731] opened 2022-04-07 18:42 UTC
![image](https://user-images.githubusercontent.com/25996703/162272925-53c6dc23-625c-4aba-bd1e-d0b2d975241b.png)
![image](https://user-images.githubusercontent.com/25996703/162274141-389a3361-f609-4ab9-8b1c-80f7d35977d2.png)
I created a table and when I sql query everything works fine. but when I use ibis, it gives the error above.

```
hive_cursor.execute('CREATE TABLE default.demo_table_ibis4 (day STRING, sales INTEGER)')
hive_cursor.execute("insert into default.demo_table_ibis4 values ('Monday', 50)")
hive_cursor.execute("insert into default.demo_table_ibis4 values ('Monday', 20)")
hive_cursor.execute("insert into default.demo_table_ibis4 values ('Tuesday', 50)")
hive_cursor.execute("insert into default.demo_table_ibis4 values ('Tuesday', 100)")

hive_cursor.execute('SELECT * FROM default.demo_table_ibis4 LIMIT 100')

hive_cursor.execute("SELECT day, avg(sales) as avg FROM default.demo_table_ibis4 group by day ")

df_hive = pd.DataFrame(hive_cursor.fetchall(), columns=[col[0] for col in hive_cursor.description])
df_hive

df_hive.groupby("demo_table_ibis4.day").mean("demo_table_ibis4.sales")

ibis.options.interactive = True
ibis.options.verbose = True

hello_world = client_ibis.database("default").table('demo_table_ibis4')

hello_world

hello_world \
    .group_by('day') \
    .aggregate( \
         avg=hello_world.sales.mean() \
      ) \
 .execute()
```

**Comment by cpcloud** [comment] 2022-04-07 18:50
Hi @z7ye can you answer these questions?

## What backend are you using?
## What version of `ibis-framework` are you using?
## What version of Python are you using?

**Comment by z7ye** [comment] 2022-04-07 18:50
![image](https://user-images.githubusercontent.com/25996703/162275621-54b362c1-ad27-4e6c-a684-02a1cb23d7d8.png)

**Comment by z7ye** [comment] 2022-04-07 18:52
Hi @cpcloud I am using ibis 2.0.0. python 3.7 and operating system is linux.

**Comment by z7ye** [comment] 2022-04-07 18:52
backend is impala

**Comment by cpcloud** [comment] 2022-04-07 18:59
> ![image](https://user-images.githubusercontent.com/25996703/162275621-54b362c1-ad27-4e6c-a684-02a1cb23d7d8.png)

This looks more like a question, let's try and keep that separate from your original issue.

**Comment by cpcloud** [comment] 2022-04-07 18:59
> backend is impala

What version of impala?

**Comment by z7ye** [comment] 2022-04-07 20:16
![image](https://user-images.githubusercontent.com/25996703/162288730-d6f9c1a3-3dc2-4536-8613-70eb8fa89f83.png)

**Comment by cpcloud** [comment] 2022-04-07 20:28
@z7ye Can you show the version of impala server?

**Comment by z7ye** [comment] 2022-04-07 20:40
Hi @cpcloud I am actually connecting to Hive server.

**Comment by cpcloud** [comment] 2022-04-08 10:07
@z7ye It looks like you need to enable the position alias feature. See [this page](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+GroupBy#LanguageManualGroupBy-GroupBySyntax) for details, but here's the important bit:

> In `groupByExpression` columns are specified by name, not by position number. However in [Hive 0.11.0](https://issues.apache.org/jira/browse/HIVE-581) and later, columns can be specified by position when configured as follows:
>
> * For Hive 0.11.0 through 2.1.x, set [hive.groupby.orderby.position.alias](https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.groupby.orderby.position.alias) to true (the default is false).
> * For Hive 2.2.0 and later, set [hive.groupby.position.alias](https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.groupby.position.alias) to true (the default is false).

You can enable this feature using one of the configuration methods [here](https://cwiki.apache.org/confluence/display/Hive/AdminManual+Configuration#AdminManualConfiguration-ConfiguringHive).

Closing this out, thanks for the report!

**Closed by cpcloud** 2022-04-08 10:07 UTC

**Comment by cpcloud** [comment] 2022-04-08 10:09
I can confirm that this setting allows `GROUP BY 1` to work using the docker compose setup here: https://github.com/big-data-europe/docker-hive.
