### ISSUE TITLE
bug: Unsupported cast from None to pyarrow

### ISSUE THREAD

**Issue by liudvikasakelis** [ibis-project/ibis#9543] opened 2024-07-10 12:32 UTC
### What happened?

```
ibis.set_backend("duckdb")
ibis.memtable({'a':[1], 'b':[None]}).to_pyarrow()
```
Gives 
```
pyarrow.lib.ArrowNotImplementedError: Unsupported cast from int32 to null using function cast_null
```
I suspect I'll get a workaround working, but it still looks like a bug. This bug doesn't appear on pandas backend.

### What version of ibis are you using?

9.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ncclementi** [comment] 2024-07-18 16:55
@liudvikasakelis thanks you for opening this issue. Looking at this, seems like the error comes from pyarrow but I'm not quite sure if this is expected, need to investigate. In the meantime here is a work around

```python
ibis.memtable({'a':[1], 'b':[np.nan]}).to_pyarrow()
```

**Comment by ncclementi** [comment] 2024-07-18 17:12
@liudvikasakelis I'll close this issue as it is not a bug on Ibis, but a consequence of DuckDB's behavior and a workaround was provided.

**Closed by ncclementi** 2024-07-18 17:12 UTC
Labels: bug
