### ISSUE TITLE
feat: add a table_exists(table_name) api

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#9223] opened 2024-05-21 17:18 UTC
### Is your feature request related to a problem?

i have to use list_tables and check if name exist in the list results, but this approach is too slow for a lot of backends, especially for data warehouses with thousands of tables, need a better api to check the table existence. 

### What is the motivation behind your request?

I am trying to use a ibis way to check table existence so i do not need to construct a raw query against the information schema table for each backend.

### Describe the solution you'd like

add a new ibis table_exists api.

### What version of ibis are you running?

3.2.0

### What backend(s) are you using, if any?

DuckDB, BigQuery, Snowflake, MySQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment] 2024-05-21 17:31
Hi @ruiyang2015 -- I'm going to close this out as a duplicate of #9215

**Closed by gforsyth** 2024-05-21 17:31 UTC
Labels: feature
