### ISSUE TITLE
sql server support ?

### ISSUE THREAD

**Issue by stonebig** [ibis-project/ibis#806] opened 2016-03-27 18:32 UTC

**Comment by costrouc** [comment] 2019-07-18 15:05
What would be necissary to add sql server support? It looks like sqlalchemy already supports sql server via pyodbc.

**Comment by cpcloud** [comment] 2019-07-18 15:51
You'd have to do something similar to what's being done in the postgresql backend. Most of the work lies in a few key areas:

#. Writing the initial client
#. Implementing the translation rules where they don't already exist or the defaults don't work for MSSQL's dialect
#. Setting up a reproducible test harness
#. Getting the CI to pass

Happy to help you get started. I would suggest looking at `ibis/sql/postgres/client.py` and then continuing to dig around from there.

Let me know if you have questions. We also have a gitter chat room if that's helpful.

**Comment by costrouc** [comment] 2019-07-28 18:16
@cpcloud thank you for the help. It looks like our client has significant interest in this feature so I will be working to add sql server support. For now I will be testing with a local docker sql server provided by microsoft. Looks like this will be easy enough to integrate with your existing docker-compose.yml with azure pipelines.

**Comment by scottcode** [comment] 2019-10-17 15:06
@costrouc Steps 1 and 2 mentioned by @cpcloud (writing the client and translation rules) include adding a `sql_server` folder under `ibis/ibis/sql` with `api.py`, `client.py`, and `compiler.py` modules that mimic the corresponding modules found in the other `ibis/ibis/sql` backend folders.

**Comment by costrouc** [comment] 2019-10-17 15:17
@scottcode here is the PR that I am working on https://github.com/ibis-project/ibis/pull/1997. Right now limitting the supported operations to get the Pr merged

**Comment by kvemani** [comment] 2020-03-18 06:51
@stonebig @costrouc @scottcode Hi folks, I work in Microsoft SQL Server group, and I am interested in contributing to this project. Will be great if you can let me know where to start, issues I can start contributing to, etc. Excited to be part of this!

**Comment by costrouc** [comment] 2020-03-18 15:34
@kvemani thanks for your interest in contributing to the sql server backend to ibis! I am currently trying to get https://github.com/ibis-project/ibis/pull/1997 merged. It is close but I will admit in the past month I haven't been pushing this PR as much. This PR only covers basic SQL with SQL Server. There is a lot of work that can be done once this PR is merged. These include more complete support for date operations and string operations which have been neglected by this PR.

**Comment by kvemani** [comment] 2020-03-19 06:19
@costrouc  Thanks for letting me know. Great work so far! I'll be happy to contribute to the features you have planned after #1997 is merged. Meanwhile, if there is anything I can do to help you move faster with #1997, please let me know.

**Comment by MarcSkovMadsen** [comment] 2020-07-10 14:18
Listening in. I’m also interested in support for sql server. Especially in connection with HoloViews https://github.com/holoviz/holoviews/pull/4517#issuecomment-656688109

**Comment by kvemani** [comment] 2020-07-20 21:39
Firstly, thanks again @costrouc for the significant work on SQL Server backend. It has been a few months since our last touchpoint here, so I wanted to check with you. Are you close to merging your changes into ibis main? If you are short on time, will it be okay for me to work on merging your changes?

@costrouc @cpcloud @scottcode @stonebig Please let me know what is the best practice for this in the ibis community. Thanks so much.

**Comment by amueller** [comment] 2020-07-24 20:07
I just had a conversation with @datapythonista about having the backend in a separate repo. I think it would make sense if MS/@kvemani would own that, what do you think? @costrouc are you still working on this as a separate backend and/or would you be ok with @kvemani putting your changes in a stand-alone repo and building on it?

**Comment by costrouc** [comment] 2020-08-03 20:44
@amueller I am not currently working anymore on a separate backend and would be happy for you and @kvemani putting the changes in a stand alone repo and maintaining that. I am so happy to see this moving forward as a supported backend. Thank you!

**Comment by matthewmturner** [comment] 2020-11-27 17:29
@datapythonista @kvemani  - im quite interested in getting the ms sql backend added.  Anything I can do to help?  My understanding is we can leverage a similar implementation to postgres but this would be in a separate ibis-project repo.  im happy to get the ball rolling on this in that separate repo if its created.  

Additionally, was there any progress on determining how CI would be handled for backend tests?

**Comment by datapythonista** [comment] 2020-11-27 17:35
The sql server backend is here: https://github.com/quansight/ibis-mssql

We'll have to adapt it when we implement entrypoints and release 2.0, but should already be working with monkeypatching.

**Comment by cpcloud** [comment] 2021-12-10 22:21
Closing, since there's a backend for this now.

**Closed by cpcloud** 2021-12-10 22:21 UTC
Labels: backends - sqlalchemy

**Comment by jreback** [comment] 2021-12-10 22:24
do we have a doc page on available backends that are not in core?

**Comment by cpcloud** [comment] 2021-12-10 22:53
We do not. Definitely in scope to have that.
