### ISSUE TITLE
bug(duckdb): percent signs aren't escaped correctly in `.case()`

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7103] opened 2023-09-08 20:37 UTC
### What happened?

EDIT: I originally filed this as a repr bug, but it actually is a bug with .case()

```python
t = ibis.examples.penguins.fetch()
cased = ibis.case().when(t.sex == "male", r"%").else_("").end()
added = r"%" + _.sex
t.select("sex", added=added, cased=cased)
```

results in (note the double %%, should be a single %)
```
┏━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓
┃ sex    ┃ added   ┃ cased  ┃
┡━━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩
│ string │ string  │ string │
├────────┼─────────┼────────┤
│ male   │ %male   │ %%     │
│ female │ %female │ ~      │
│ female │ %female │ ~      │
│ NULL   │ %       │ ~      │
│ female │ %female │ ~      │
│ male   │ %male   │ %%     │
│ female │ %female │ ~      │
│ male   │ %male   │ %%     │
│ NULL   │ %       │ ~      │
│ NULL   │ %       │ ~      │
│ …      │ …       │ …      │
└────────┴─────────┴────────┘
```

The problem is that this is getting compiled to:

```sql
SELECT
  t0.sex,
  CONCAT(COALESCE(CAST('%' AS TEXT), ''), COALESCE(CAST(t0.sex AS TEXT), '')) AS added,
  CASE WHEN (
    t0.sex = 'male'
  ) THEN '%%' ELSE '' END AS cased
FROM _ibis_examples_penguins_3bvfvrlqvvfxtohz4nsbvfdxca AS t0
```

Using .ifelse() works fine.

### What version of ibis are you using?

6.1.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment] 2023-09-08 21:57
This is due to the patch made [here](https://github.com/ibis-project/ibis/pull/5544) where case statements are compiled with bound literals to work around a bug in duckdb < 0.7.0. I spent some time playing around with sqlalchemy to see if we could fix this behavior, but haven't been able to. Perhaps @cpcloud knows a trick here.

Since the case statement parametrization issue was fixed in duckdb 0.7.0 (released in Feb 2023) we _could_ potentially remove this patch entirely, reverting back to the base case statement compiler which won't result in the escaping behavior here. Alternatively I suspect the upcoming sqlglot compiler (#6996) may be able to work around this issue in a cleaner way. SQLAlchemy is powerful, but the layers make it a bit complicated to debug :/.

**Comment by NickCrews** [comment] 2023-09-08 23:02
lol what a circle we've made 🙃:

1. notice upstream problem
2. add workaround for problem
3. upstream problem is fixed
4. now our workaround is the problem

Could we make that patch conditional depending on `duckdb.__version__ < 0.7.0`?

**Comment by cpcloud** [comment] 2023-09-12 09:24
I think it's probably okay to bump the lower bound of duckdb to the latest version and to continue to do periodically until duckdb reaches 1.0.0.

**Comment by cpcloud** [comment] 2023-09-12 09:28
@NickCrews I am unable to reproduce this on `master`. Can you try with the latest commit?

**Closed** 2023-09-12 16:01 UTC
Labels: bug, duckdb
