### ISSUE TITLE
bug: sqlite database URL doesn't work with ibis.connect() on windows with absolute path

### ISSUE THREAD

**Issue by mgaspary** [ibis-project/ibis#5680] opened 2023-03-07 09:35 UTC
### What happened?

According to the code comments of `ibis.connect()` function, an absolute database file path should work for SQLite:
(from `ibis.connect()` function description).
```python
"""
    Examples
    --------
    ...
    Connect to an on-disk sqlite database:
    >>> con = ibis.connect("sqlite://relative/path/to/data.db")
    >>> con = ibis.connect("sqlite:///absolute/path/to/data.db")
    ...
"""
```
However, if I use Windows absolute path for a database file, it gives OperationalError
```python
import sqlalchemy_utils
import ibis

filename = r"C:/some/absolute/path/database.db"
eng_url = f"sqlite:///{filename}"
if not sqlalchemy_utils.database_exists(eng_url):
    sqlalchemy_utils.create_database(eng_url)
assert sqlalchemy_utils.database_exists(eng_url)

conn = ibis.connect(filename)  # works fine
conn = ibis.connect(eng_url)  # raises sqlite3.OperationalError
```

### What version of ibis are you using?

python 3.10.9
ibis-framework 4.1.0
sqlalchemy 1.4.46

### What backend(s) are you using, if any?

SQLite

### Relevant log output

```sh
Error message:
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment] 2023-03-07 11:59
👋🏻 Hi @mgaspary! Welcome to the project :)

Thanks for the issue.

Interestingly, `sqlite:///absolute/path` does work on Linux.

We'll take a look at this for 5.0!

**Comment by cpcloud** [comment] 2023-03-07 12:48
@mgaspary I think the issue is that you're trying to call `ibis.connect` with an invalid path:

```
/C:/some/absolute/path/database.db
```

is not a valid absolute path on Windows, so `sqlite:///C:/some/absolute/path/database.db` isn't a valid sqlalchemy URL.

However `C:/some/absolute/path/database.db` is already an absolute path, so that should work.

We have tests for URLs with absolute paths on Windows and they are passing on `master`, so I'm going to close this out!

Thanks again for the report.

**Closed by cpcloud** 2023-03-07 12:48 UTC
Labels: bug, backends - sqlite

**Comment by mgaspary** [comment] 2023-03-07 14:03
@cpcloud oh, interesting. Indeed, it is working fine with `sqlite://C:/some/absolute/path/database.db`.
I was using `ibis.connect()` indirectly through SQLalchemy `engine.url`. And for SQLalchemy `str(engine.url)` for SQLite should have `///` in the beginning ([here](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlite)).

So if I extend my example:
```python
import sqlalchemy_utils
import sqlalchemy
import ibis

filename = r"C:/some/absolute/path/database.db"
eng = sqlalchemy.engine.create_engine(f"sqlite:///{filename}")
eng_url = str(eng.url)
if not sqlalchemy_utils.database_exists(eng_url):
    sqlalchemy_utils.create_database(eng_url)
assert sqlalchemy_utils.database_exists(eng_url)

conn = ibis.connect(filename)  # works fine
eng_url_fixed = f"sqlite://{filename}"
conn = ibis.connect(eng_url)  # works fine
conn = ibis.connect(eng_url)  # raises sqlite3.OperationalError
```

**Comment by jcrist** [comment] 2023-03-07 14:34
Yeah, `sqlalchemy` is unique among systems processing DB URIs in that it expects four leading slashes for an absolute path, not 3. We went with the more common pattern.

Thank of it more as:

```python
uri = "sqlite://{path_to_db}"
```

where `path_to_db` can be an absolute or relative path (optionally including a drive designator on windows). If you can think of a better (but still concise) way of demonstrating this in the docstring, could you please open a PR with a fix? We definitely want to make sure our docs are accurate and useful here.

**Comment by mgaspary** [comment] 2023-03-07 15:42
@jcrist ok, so I guess I should blame SQLalchemy URL template for SQLite then, if it is not a standard

I don't see the alternative here, since SQLite `"sqlite://path-to-db"` is usually a standard for other processing DB systems.
In my project I just created a wrapper around `ibis.connect()` that takes SQLalchemy engine as input and gives connection back.
In that case I'm able to detect SQLite engine by `engine.name` and extract the DB filename from URL to provide it to `ibis.connect()`

Sorry for bothering you, guys
