### ISSUE TITLE
bug: Incorrect datetime dtypes with postgres backend

### ISSUE THREAD

**Issue by robdmc** [ibis-project/ibis#5921] opened 2023-04-05 19:25 UTC
## Postgres database
* Any postgres table with a timestamp('UTC') field

## Same snippet run under ibis 4.1.0 and 5.0.0
```python
visit = global_connection.table("hello_visit")

print("\n\n---")
print("ibis version", ibis.__version__)
print("sqlalchemy version", sqlalchemy.__version__)
print("psycopg2 version", psycopg2.__version__)


print("\n\n---")
print("schema")
print(visit[["when_started"]].schema())

visit = visit[visit.when_submitted >= pd.Timestamp("1/1/2021")]
print("\n\n---")
print("result type")
print('***')
print(visit.head().execute().when_submitted.dtype)
print('***')
```
### Ibis 4.1.0 results Results
```
---
ibis version 4.1.0
sqlalchemy version 1.4.47
psycopg2 version 2.9.3 (dt dec pq3 ext lo64)


---
schema
ibis.Schema {
  when_started  !timestamp('UTC')
}


---
result type
***
datetime64[ns, UTC]
***


---
```

### Ibis 5.0.0 Results
```
---
ibis version 4.1.0
sqlalchemy version 1.4.47
psycopg2 version 2.9.3 (dt dec pq3 ext lo64)


---
schema
ibis.Schema {
  when_started  !timestamp('UTC')
}


---
result type
***
object
***


---
```

### What version of ibis are you using?

5.0.0

### What backend(s) are you using, if any?

postgres

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment] 2023-04-05 19:46
@robdmc Hello! Thanks for the issue.

Can you show the data? I can't reproduce this on `master`.

**Comment by cpcloud** [comment] 2023-04-05 19:47
Also, in your second print out I see `ibis version 4.1.0`. Is that correct?

**Comment by cpcloud** [comment] 2023-04-06 12:31
Hm, there's also a discrepancy in your schemas and your expression.

Your schemas show a single `when_started` column, but your ibis expression is using `when_submitted`, so something is amiss here.

Please provide the entire example you're using to reproduce this bug and we'll get on it!

**Comment by robdmc** [comment] 2023-04-06 14:44
@cpcloud This is on proprietary database I can't share.  Will try and reproduce in dummy db in  docker container for you.  It's possible I'm doing something dumb.

**Comment by robdmc** [comment] 2023-04-06 17:47
@cpcloud I DM'd you on Gittr about this, but long story short is I can't reproduce it either on a dummy database.

**Feel free to close this issue until I can reliably reproduce it.**  

My money right now is that there is just something hokey with my install.

Here's the workaround that works for me.  When I see the timestamp getting turned into strings, I just explicityly select all columns with code like
```python
my_table = my_table[list(my_table.columns]]
```
at the top level, and at that point everything just works.  I have no idea.

**Comment by cpcloud** [comment] 2023-04-06 18:36
Closing for now. Please comment if you're able to reproduce!

**Closed by cpcloud** 2023-04-06 18:36 UTC
Labels: bug, question, not reproducible
