### ISSUE TITLE
feat: Simplify converting to DuckDB (and other backends)

### ISSUE THREAD

**Issue by Riezebos** [ibis-project/ibis#8808] opened 2024-03-27 23:20 UTC
### Is your feature request related to a problem?

The DuckDB backend is fast and supports a lot of operations. When I am running into issues related to supported operations on e.g. BigQuery or Postgres, a solution I've found for this is getting the table into DuckDB using e.g.:

```
duckdb_con = ibis.duckdb.connect()
pyarrow_table = pg_con.table("my_table").to_pyarrow()
my_table = duckdb_con.sql("select * from pyarrow_table")
```

Or storing it as parquet first and then loading the parquet with `ibis.read_parquet()`

### Describe the solution you'd like

I'm not sure, but here is a proposal:
It could be a method similar to `.to_pyarrow()` and `.to_pandas()`, maybe `.to_ibis()` or `.to_backend()`

By default, it would try to export the result of the expression from the backend that is being used as an Arrow table and import it into the configured default backend (or just to DuckDB).

It could also have an argument `backend`, where a backend can be entered and if it is supported (mainly via ADBC I guess) the data can be easily transferred.

This would also improve the composability of the data ecosystem.

### What version of ibis are you running?

8.0.0

### What backend(s) are you using, if any?

DuckDB, Postgres, BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment] 2024-03-28 14:33
hi @Riezebos, I'm inclined to close this as a duplicate of https://github.com/ibis-project/ibis/issues/8115, but can you confirm that would satisfy your needs here? this would allow you to create/insert tables from any (or at least many) backend(s) into DuckDB

**Comment by gforsyth** [comment] 2024-03-28 15:13
Agree with @lostmygithubaccount on this.
Also as a slight improvement to the pattern above, you can explicitly create a table from a pyarrow table, so instead of the `sql` call, you can do:

```python
duckdb_con = ibis.duckdb.connect()
my_table = duckdb_con.create_table("my_table", pg_con.table("my_table").to_pyarrow())
```

**Comment by Riezebos** [comment] 2024-03-28 15:57
Thanks for the quick response!

If I understand correctly, #8115 proposes to do the same as the code snippet from @gforsyth without `.to_pyarrow()`. My request would be a version that can be used when chaining expressions. Some of my favourite features of ibis are:

- Chaining lots of operations
- Not having to give explicit names to tables with _

This also makes it easier to copy a snippet from one chained expression to another.

For me, there would be value in just being able to add `.to_backend(ddb_con)` at some point in an expression, and then maybe adding another `.to_backend(pg_con)` at the end.

**Comment by lostmygithubaccount** [comment] 2024-03-29 18:18
hi @Riezebos, I am going to close this out as a duplicate of #8115. there are a few workarounds here noted above. we hear you on having `to_backend()`, but also think this could be confusing to add a new API, especially if it is to be used in the middle of a longer chain of expressions. generally, those eager `to_*` methods should come at the end of an expression chain

do keep the feedback coming, we appreciate it!

**Closed by lostmygithubaccount** 2024-03-29 18:18 UTC
Labels: feature
