### ISSUE TITLE
bug(duckdb, sqlite): setting a file-backed backend doesn't write to file

### ISSUE THREAD

**Issue by liudvikasakelis** [ibis-project/ibis#9946] opened 2024-08-27 18:42 UTC
### What happened?

Setting backend to a database file doesn't write any data to that file: 
```
ibis.set_backend(ibis.duckdb.connect('tmp.ddb'))
table_list = [ibis.memtable(parse_xml(filename)) for filename in filename_list]
```
I expected to have each table in the tmp.ddb file, however the file only gets created but doesn't contain any data. I don't think documentation mentions or promises this, but I feel this is implied? `ibis.duckdb.connect()` backend is memory-backed, therefore all tables remain in-memory; it would follow that a file-based DB backend would store data in that file. 

Backing such tables in a file would be a big win for data workflow scalability (no longer limited by available memory). 

### What version of ibis are you using?

9.3.0

### What backend(s) are you using, if any?

DuckDB and SQLite show same described behaviour.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment] 2024-08-27 19:20
Hi @liudvikasakelis!  

`memtable`s create in-memory tables, and they are transient by design.  If you want the tables to persist, you can pass the `memtable`s to `create_table`, either using the generated `memtable` name or adding your own:

```python
con = ibis.duckdb.connect('tmp.ddb')
ibis.set_backend(con)
table_list = [ibis.memtable(parse_xml(filename)) for filename in filename_list]

for table in table_list:
    con.create_table(table.get_name(), table)
```

**Comment by cpcloud** [comment] 2024-08-28 02:03
Closing, thanks for the discussion!

As @gforsyth notes, these are working as intended.

**Closed by cpcloud** 2024-08-28 02:03 UTC
Labels: bug
