### ISSUE TITLE
feat/bug: order_by aggs in groupbys

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#9710] opened 2024-07-29 04:19 UTC
### Is your feature request related to a problem?

Not sure if this is a feature request or bug. See these examples (EDIT: moved these to be more linear as requested)

```python
import ibis
from ibis import _
ibis.options.interactive = True
orders = ibis.memtable({"cust": [1, 1, 1, 2, 2], "date": [3, 2, 1, 9, 8], "amount": [1, 2, 3, 4, 5]})
```

Collect the order amounts for each customer, ordered by date:
This is what I want, and this works. Note that the order_by
comes BEFORE the group_by.

```python
e1 = orders.order_by("date").group_by("cust").agg(earliest_first=_.amount.collect())
print(ibis.to_sql(e1))
display(e1)
```

```
SELECT
  "t1"."cust",
  ARRAY_AGG("t1"."amount") FILTER(WHERE
    "t1"."amount" IS NOT NULL) AS "earliest_first"
FROM (
  SELECT
    *
  FROM "ibis_pandas_memtable_c6coi73fkzerleojlnpmmwq2va" AS "t0"
  ORDER BY
    "t0"."date" ASC
) AS "t1"
GROUP BY
  1
┏━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ cust  ┃ earliest_first ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━┩
│ int64 │ array<int64>   │
├───────┼────────────────┤
│     1 │ [3, 2, ... +1] │
│     2 │ [5, 4]         │
└───────┴────────────────┘
```

But if I switch the order_by to be AFTER the group_by, then it doesn't work as
I would expect.
Looking at the SQL, there is no ORDER BY anywhere.

```python
e2 = orders.group_by("cust").order_by("date").agg(earliest_first=_.amount.collect())
print(ibis.to_sql(e2))
display(e2)
```

```
SELECT
  "t0"."cust",
  ARRAY_AGG("t0"."amount") FILTER(WHERE
    "t0"."amount" IS NOT NULL) AS "earliest_first"
FROM "ibis_pandas_memtable_c6coi73fkzerleojlnpmmwq2va" AS "t0"
GROUP BY
  1
┏━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ cust  ┃ earliest_first ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━┩
│ int64 │ array<int64>   │
├───────┼────────────────┤
│     2 │ [4, 5]         │
│     1 │ [1, 2, ... +1] │
└───────┴────────────────┘
```

But if you switch to .agg(), then the results are ordered.
(but I want an agg, not a mutate, so this doesn't work for me)

```python
e3 = orders.group_by("cust").order_by("date").mutate(earliest_first=_.amount.collect())
print(ibis.to_sql(e3))
```

```
display(e3)
SELECT
  "t0"."cust",
  "t0"."date",
  "t0"."amount",
  ARRAY_AGG("t0"."amount") FILTER(WHERE
    "t0"."amount" IS NOT NULL) OVER (PARTITION BY "t0"."cust" ORDER BY "t0"."date" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "earliest_first"
FROM "ibis_pandas_memtable_c6coi73fkzerleojlnpmmwq2va" AS "t0"
┏━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ cust  ┃ date  ┃ amount ┃ earliest_first ┃
┡━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━┩
│ int64 │ int64 │ int64  │ array<int64>   │
├───────┼───────┼────────┼────────────────┤
│     2 │     8 │      5 │ [5, 4]         │
│     2 │     9 │      4 │ [5, 4]         │
│     1 │     1 │      3 │ [3, 2, ... +1] │
│     1 │     2 │      2 │ [3, 2, ... +1] │
│     1 │     3 │      1 │ [3, 2, ... +1] │
└───────┴───────┴────────┴────────────────┘
```

Now I'm getting out of the territory of "bug fix", and into "feature request" territory.
Maybe I want different orderings for different aggs? Duckdb supports this
with the "ORDER BY" clause in its agg functions.

Now I'm getting out of the territory of "bug fix", and into "feature request" territory.
Maybe I want different orderings for different aggs? Duckdb supports this
with the "ORDER BY" clause in its agg functions.

```python
e4 = orders.group_by("cust").agg(
    latest_first=_.amount.collect(order_by=_.date.desc()),
    earliest_first=_.amount.collect(order_by=_.date.asc()),
)
```

One thing we would have to talk about is what to do where the orderings are
specified twice, eg
groub_by().order_by("x").agg(_.x.collect(order_by="y"))
This could be a potential other way of spelling what I want,
that doesn't require changing the API. But IDK might be semantically confusing.

```python
e5 = orders.group_by("cust").agg(earliest_first=_.amount.collect().over(order_by="date"))
```

Or, if we could order columns, then we could do this:

```python
e6 = orders.group_by("cust").agg(earliest_first=_.amount.order_by("date").collect())
```

but this probably isn't worth opening up the Column.order_by() API, as has
been discussed in other issues.

### What is the motivation behind your request?

When collecting elements into an array I want them in a particular order. When using first() or last(), I think you could also workaround using .argmin() or something. But array aggregation has no workaround, I need to be able to control the element order there.

I want the `collect(order_by)` API because I want to be able to write a util function that look something like

```python

def summarize(gb, aggs, other_option):
    gb = prep(gb, other_option)
    ...
    return gb.agg(**aggs)

aggs = {
    "earliest_first": _.amount.collect(order_by=_.date),
    ...
}

summarize(t.group_by("x", aggs, foo)
```

in other words the logic that chooses what to group_by is separate from the logic that determines what aggs to compute. Currently these two steps have to be interwoven in code.
        
    

### Describe the solution you'd like

I think there are some slightly orthogonal decisions we could make:
- should we make `group_by().order_by()` behave the exact same as `order_by().group_by()`?
- should we add `order_by` option to order-dependent aggs such as collect(), first(), etc? I would assume these should error if executed on a backend that doesn't support it. I'm not sure what the story is on other backends.

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

personally, duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment] 2024-07-29 13:40
Hey @NickCrews -- thanks for raising this.  Can I prevail upon you to format the example in a more linear way?  Between the github-imposed scrollbars, the inline comments, and the results in a separate output, it's very hard to visually parse.

**Comment by cpcloud** [comment] 2024-07-29 15:58
This issue is mixing up way too many things. Let's split it up a bit.

## Issue 1

The first issue is with assumptions about what effect `order_by` has in a subquery.

We should clarify this somewhere, but using an `order_by` call without a `head`/`limit` call at the same level, in a subquery, **will not** in general preserve row ordering.

MS SQL actually forbids `ORDER BY` in subqueries if they don't have a limit. I think that's probably too annoying for us to do, but it's *an* approach.

This expression:

```python
e1 = orders.order_by("date").group_by("cust").agg(earliest_first=_.amount.collect())
```

can *validly* execute without ever ordering by `date`.

Now, there are a few things we could do here, but we don't do them (and may never!):

1. collapse these three operations into one, which means the order by would be respected
2. move all order by to their outermost valid position and remove them from subqueries, not sure what the pitfalls there are.

## Issue 2

The second query not rendering the `order_by` might be a bug.

```python
e2 = orders.group_by("cust").order_by("date").agg(earliest_first=_.amount.collect())
```

I would expect the `order_by` to render at least *somewhere*.

## Issue 3

```python
e3 = orders.group_by("cust").order_by("date").mutate(earliest_first=_.amount.collect())
```

This is intended behavior, it's based on the equivalent dplyr functionality.

## Issue 4

```python
e4 = orders.group_by("cust").agg(
    latest_first=_.amount.collect(order_by=_.date.desc()),
    earliest_first=_.amount.collect(order_by=_.date.asc()),
)
```

A good chunk of our backends support this, and its on the roadmap.

## Issue 5

```python
e5 = orders.group_by("cust").agg(earliest_first=_.amount.collect().over(order_by="date"))
```

`over` is for window functions, and we're not going to start allow those in aggregates, because that's not well-defined.

## Issue 6

```python
e6 = orders.group_by("cust").agg(earliest_first=_.amount.order_by("date").collect())
```

Definitely not 😅

**Comment by NickCrews** [comment] 2024-07-29 16:45
First, I really really appreciate the detailed response here.

## Issue 1

Just to be clear, you are saying that the collected array in `e1 = orders.order_by("date").group_by("cust").agg(earliest_first=_.amount.collect())` only has an ordering in duckb, if I ran that on MSSQL there would be no guarantee? Which implies that ibis isn't ever going to try to enforce these semantics, and I probably shouldn't rely on them? This is just fine with me as long as we get option 2 to work, I find option 2 (groupby, then order within each group, obviously the ordering is within each group) to be much more clear than 1 (order by, then group by? IDK is the ordering supposed to be preserved??)

If so, then is there anything we can do to prevent footguns? ie the ordering is working for me on duckdb, but if I switched to something else I would get burned. So maybe we (warn, error) if someone does a group_by() on an ordered relation where there is no head/limit? IDK that seems like that might be more than we want to tackle.

## Issue 2

I would love to consider this a bug, and fix it so that THIS was the way to spell the thing I want to do. I don't think I have the knowledge to implement this fix though.

## Issue 3

Cool, I think we're on the same page this is intended behavior. I was just using this as a contrast (gb->ob->mutate has an ordering, gb->ob->agg does not)

## Issue 4

Sweet, love to hear that's on the roadmap. If you did a tiny PR that implemented it for an op or two, I might be able to take that as a framework and do it for the rest.

## Issues 5 and 6

Sounds good, I think we are on the same page about these two not being a good idea.

## Moving forward

I propose:
- I open an issue for fixing issue 2
- We move further discussion of issue 4 to https://github.com/ibis-project/ibis/issues/9170 (oops, didn't adequately search issue before I opened this one, sorry!)
- We close this issue as completed

**Comment by cpcloud** [comment] 2024-07-29 16:47
Solid plan, let's do it!

**Comment by NickCrews** [comment] 2024-07-29 17:13
Do you have any thoughts on my footgun mitigation idea I mentioned under issue 1?

**Comment by gforsyth** [comment] 2024-07-29 19:30
I'm going to close this out as completed since @NickCrews opened #9716 (thank you!) and further discussion of example 4 can happen over in #9170.

**Closed by gforsyth** 2024-07-29 19:30 UTC
Labels: feature
