### ISSUE TITLE
OmniSciDB: Could not find signature for convert: <CategoricalDtype, String, Series>

### ISSUE THREAD

**Issue by mikehinchey** [ibis-project/ibis#1920] opened 2019-08-13 06:52 UTC
Selecting a string column with GPU results gives an error.

Connect with `execution_type=2` for GPU/cudf results.

```python
t = con.table('omnisci_states')
t.info()
```

```
...
name      String(nullable=True)52        
```

```python
x = t['name']
x.compile()
```

```
'SELECT "name"\nFROM omnisci_states'
```

```python
x.execute()
```

```
...

/opt/conda/lib/python3.7/site-packages/ibis_framework-1.2.0-py3.7.egg/ibis/pandas/client.py in ibis_schema_apply_to(schema, df)
    331 
    332         if not_equal or dtype == dt.string:
--> 333             df[column] = convert(col_dtype, dtype, col)
    334 
    335     return df

opt/conda/lib/python3.7/site-packages/multipledispatch-0.6.0-py3.7.egg/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    273                 raise NotImplementedError(
    274                     'Could not find signature for %s: <%s>' %
--> 275                     (self.name, str_signature(types)))
    276             self._cache[types] = func
    277         try:

NotImplementedError: Could not find signature for convert: <CategoricalDtype, String, Series>
```

For contrast, this succeeds using the pymapd connection:

```python
c = con.con.select_ipc_gpu(x.compile())
c.to_pandas()[:5]
```

**Comment by xmnlab** [comment] 2019-08-13 15:50
@mikehinchey does the error occur just after `x.execute()`?

**Comment by mikehinchey** [comment] 2019-08-13 17:05
@xmnlab yes, after `execute()` when it's converting the results.

**Comment by xmnlab** [comment] 2019-09-11 00:02
@mikehinchey for some reason the error you have seems to be related to pandas backend (`ibis/pandas/client.py `)

I am working now on a PR that adds execution_type support to `execute` method .. and I fixed some issues there and it seems your problem doesn't show up. https://github.com/ibis-project/ibis/pull/1964

so probably it will be fixed!

**Comment by xmnlab** [comment] 2019-09-11 20:06
@mikehinchey actually I could reproduce the error here. I am investigating that now.

**Comment by xmnlab** [comment] 2019-09-11 20:41
ibis is treating this column as a category .. and it seems cudf is not allowing this conversion.

probably related: https://github.com/rapidsai/cudf/issues/1664

I am trying to install the new cudf 0.9 to check if the problem was fixed

**Closed** 2020-02-28 01:20 UTC
Labels: omnisci
