### ISSUE TITLE
bug: executing unbound expression in pandas doesn't work like other backends

### ISSUE THREAD

**Issue by dlovell** [ibis-project/ibis#8778] opened 2024-03-26 12:50 UTC
### What happened?

Using the code from https://ibis-project.org/how-to/extending/unbound_expression, running against duckdb and datafusion works while running against pandas does not

```
import pathlib         
                                                                      
import ibis            
from ibis import _


NAME = "diamonds"


def make_expr(name=NAME):
    schema = {
        "carat": "float64",
        "cut": "string",
        "color": "string",
        "clarity": "string",
        "depth": "float64",
        "table": "float64",
        "price": "int64",
        "x": "float64",
        "y": "float64",
        "z": "float64",
    }
    expr = (
        ibis.table(schema, name=name)
        .group_by(["cut", "color"])
        .agg(carat=_.carat.mean())
        .pivot_wider(
            names=("Premium", "Ideal"), names_from="cut", values_from="carat", names_sort=True, values_agg="mean"
        )
    )
    return expr


def make_con(backend, name=NAME):

    def ensure_data(path=pathlib.Path(f"{NAME}.parquet")):
        if not path.exists():
            getattr(ibis.examples, NAME).fetch().to_parquet(path)
        return path

    path = ensure_data()
    con = getattr(ibis, backend).connect()
    con.read_parquet(path, table_name=name)
    return con


expr = make_expr()
for backend in ("duckdb", "datafusion", "pandas"):
    try:
        make_con(backend).to_pandas(expr)
        print(f"backend '{backend}' works")
    except Exception as e:
        print(f"backend '{backend}' DOESN'T work")
        print("\t", e)
```
will print
```
backend 'duckdb' works
backend 'datafusion' works
backend 'pandas' DOESN'T work
         Node of type 'UnboundTable' has no data bound to it. You probably tried to execute an expression without a data source.
```

but this will work

```
def replace_unbound(expr, con):
    import ibis.expr.operations as ops
    from ibis.common.patterns import replace

    @replace(ops.UnboundTable)
    def bind_unbound_table(_, backend, **kwargs):
        return ops.DatabaseTable(name=_.name, schema=_.schema, source=backend)

    ctx = {"params": {}, "backend": con}
    return (
        expr.op()
        .replace(bind_unbound_table, context=ctx)
        .to_expr()
    )


replace_unbound(expr, make_con("pandas")).to_pandas()
```

### What version of ibis are you using?

8.0.0

### What backend(s) are you using, if any?

duckdb, datafusion, pandas

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment] 2024-03-29 18:32
Thanks for the issue and the reproducer @dlovell !

We've rewritten the `pandas` backend since 8.0 and on current `main` the output of your script is:

```
backend 'duckdb' works
backend 'datafusion' works
backend 'pandas' works
```

I'm going to close this out as fixed in 9.0 -- if you're feeling adventurous you can try out a pre-release with `python -m pip install --pre -U 'ibis-framework[pandas,datafusion,polars]'`

**Closed** 2024-03-29 18:32 UTC
Labels: bug, pandas
