### ISSUE TITLE
feat(bigquery): Support for BigQuery's GENERATE_ARRAY syntax

### ISSUE THREAD

**Issue by chelsea-lin** [ibis-project/ibis#8892] opened 2024-04-04 17:15 UTC
### Is your feature request related to a problem?

Currently, Ibis doesn't seem to have a direct way to handle BigQuery's [GENERATE_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#generate_array) syntax. SQLGlot's [GenerateSeries](https://github.com/tobymao/sqlglot/blob/ed66369e0b28652d6c8db7b7abd90fc671b6e63e/sqlglot/expressions.py#L4651) node demonstrates a potential implementation approach. Would it be possible to consider adding similar support to Ibis?

### Describe the solution you'd like

With this new API, we can do:

```
import ibis
bq = ibis.bigquery.connect(project_id="bigframes-dev")
table = bq.table("bigframes-dev.ibis_gbq_testing.array_types")

offset_array = ibis.generate_array(0, ibis.least(table.x.length() - 1, table.y.length() - 1))
table_w_offset_array = table.select(offset_array, table.x, table.y)
```

### What version of ibis are you running?

main branch

### What backend(s) are you using, if any?

BigQuery. Not sure if it is applied for other backends as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment] 2024-04-04 17:33
Here's a very simple example https://ibis-project.org/posts/ibis-version-8.0.0-release/#range

**Comment by chelsea-lin** [comment] 2024-04-04 18:05
Thanks! I haven't been able to find the `ibis.range` I'm looking for. Also, regarding the generated SQL, I'm concerned about potential performance issues.  The array unpacking and re-packing operations might introduce overhead. Do you have context about that?

```
SELECT
  IF(
    NOT NULLIF(1, 0) IS NULL AND sign(1) = sign(5 - 0),
    ARRAY(
      SELECT
        ibis_bq_arr_range_bmx2itv5qbbqpm33chohjqwz3y
      FROM UNNEST(generate_array(0, 5, 1)) AS ibis_bq_arr_range_bmx2itv5qbbqpm33chohjqwz3y
      WHERE
        ibis_bq_arr_range_bmx2itv5qbbqpm33chohjqwz3y <> 5
    ),
    []
  ) AS `offset_array_0`,
  `t0`.`x`,
  `t0`.`y`
FROM `bigframes-dev`.`ibis_gbq_testing`.`array_types` AS `t0`
```

**Comment by cpcloud** [comment] 2024-04-04 18:10
@chelsea-lin If `ibis.range` doesn't exist for you then you're probably on an Ibis older than 8.0.0.

The packing and unpacking is to give `ibis.range` uniform behavior across backends. This code in particular is removing the final element to give the same semantics as python's `range`. There might be a way to calculate the upper bound directly, instead of simply filtering it out and then we could get rid of the `WHERE` clause and `ARRAY` subquery.

How would you feel about submitting a PR for that?

**Comment by cpcloud** [comment] 2024-04-04 18:18
You should also be able to define your own `generate_array` using builtin UDFs.

```python
@ibis.udf.scalar.builtin
def generate_array(start, stop, step) -> list[int]:
    ...


x = t.mutate(x=generate_array(0, 10, 1))
```

**Comment by chelsea-lin** [comment] 2024-04-04 18:48
Thanks @cpcloud for all information! The `UDF` solution looks good to me.

**Comment by cpcloud** [comment] 2024-04-04 18:51
Happy to help!

**Comment by tswast** [comment] 2024-07-09 16:48
Re-opening, because I'd like to be able to use `ibis.range` instead of UDF in BigQuery DataFrames.

Regarding upper-bound calculations, I suppose `step` is what complicates it the most, as `end` might not align fully on a step boundary. Otherwise, we could just subtract `step` to get the upper bound. I imagine some logic with `ceil` / `floor` could resolve that?

**Comment by cpcloud** [comment] 2024-07-16 19:58
You can get an empty array using `ibis.range`:

```
In [1]: from ibis.interactive import *

In [2]: con = ibis.bigquery.connect()

In [3]: con.execute(ibis.range(0))
Out[3]: []
```

I'm not following what the issue is here.

**Comment by cpcloud** [comment] 2024-07-17 16:59
Closing as resolved!

**Closed by cpcloud** 2024-07-17 16:59 UTC
Labels: feature
