### ISSUE TITLE
.create_table method does not work with BigQuery if the input table is an ibis table

### ISSUE THREAD

**Issue by aemikarafi** [ibis-project/ibis#8679] opened 2024-03-16 13:11 UTC
### What happened?

I expect is to just create a new table in BigQuery

### What version of ibis are you using?

8.0.0

### What backend(s) are you using, if any?

BigQuery

### Relevant log output

```sh
#### Environment details

  - OS type and version:
  - Python version: `Python 3.9.18`
  - pip version: `pip 24.0`
  - `google-cloud-bigquery` version: `google-cloud-bigquery==3.19.0`
  - `ibis-framework` version: `ibis-framework==8.0.0`

#### Steps to reproduce
1) Create an ibis table
2) Save the ibis table to BigQuery

#### Code example


from ibis.interactive import *
con = ibis.connect("bigquery://smart-dumb")
con.set_database("data_2023")
new = con.tables.DataCreateTable_Customer_20240125_083529
con.create_table("baba", new)


#### Stack trace

...
/~/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py:1589) if self._query_results is None or not self._query_results.complete:
...
BadRequest: 400 Syntax error: Missing whitespace between literal and alias at [1:26]; reason: invalidQuery, location: query, message: Syntax error: Missing whitespace between literal and alias at [1:26]
```
This happens because the resulting query looks like

```
CREATE TABLE smart-dumb.data_2023.baba AS WITH t0 AS (
...
)
```
there is no back ticks on the name.
I am surprised why that is, because the SELECT * FROM  from source inside has backticks, such as `smart-dumb`.data_2023.DataCreateTable_Customer_20240125_083529

A quick workaround would help.

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment] 2024-03-22 18:06
Hey @aemikarafi !

I can't reproduce this on `main` and our dataset and project_id also have the same mix of hyphens and underscores:

```python
[ins] In [1]: import ibis

[ins] In [2]: con = ibis.connect("bigquery://ibis-gbq")

[ins] In [3]: con.set_database("ibis_gbq_testing")

[ins] In [4]: astronauts = con.tables.astronauts

[ins] In [5]: con.create_table("astro2", astronauts)
Out[5]: 
DatabaseTable: astro2
  id                       int64
  number                   int64
  nationwide_number        int64
  name                     string
  original_name            string
  sex                      string
  year_of_birth            int64
  nationality              string
  military_civilian        string
  selection                string
  year_of_selection        int64
  mission_number           int64
  total_number_of_missions int64
  occupation               string
  year_of_mission          int64
  mission_title            string
  ascend_shuttle           string
  in_orbit                 string
  descend_shuttle          string
  hours_mission            float64
  total_hrs_sum            float64
  field21                  int64
  eva_hrs_mission          float64
  total_eva_hrs            float64

[ins] In [6]: astro2 = con.tables.astro2

[ins] In [7]: astro2.head().to_pyarrow()
Out[7]: 
pyarrow.Table
id: int64
number: int64
nationwide_number: int64
name: string
original_name: string
sex: string
year_of_birth: int64
nationality: string
military_civilian: string
selection: string
year_of_selection: int64
mission_number: int64
total_number_of_missions: int64
occupation: string
year_of_mission: int64
mission_title: string
ascend_shuttle: string
in_orbit: string
descend_shuttle: string
hours_mission: double
total_hrs_sum: double
field21: int64
eva_hrs_mission: double
total_eva_hrs: double
----
id: [[186,189,194,198,201]]
number: [[87,89,92,94,96]]
nationwide_number: [[1,1,1,1,1]]
name: [["Vladimir Remek","Miroslaw Hermaszewske","Georgi Ivanov","Bertalan Farkas","Pham Tuan"]]
original_name: [["NA","Miroslaw Hermaszewske","Георги Иванов Иванов","Farkas Bertalan","Phạm Tuân"]]
sex: [["male","male","male","male","male"]]
year_of_birth: [[1948,1941,1940,1949,1947]]
nationality: [["Czechoslovakia","Poland","Bulgaria","Hungry","Vietnam"]]
military_civilian: [["military","military","military","civilian","military"]]
selection: [["Air Gorce Group 6 - USSR","1976 Intercosmos Group","1978 Intercosmos Group","1978 Intercosmos Group","1979 Intercosmos Group"]]
...

[ins] In [8]: con.drop_table("astro2")
```

if you can upgrade, you might try out a recent prerelease by running

```sh
python -m pip install -U --pre 'ibis-framework[bigquery]'
```

**Comment by gforsyth** [comment] 2024-03-22 18:13
I'm going to close this out for the moment, but please ping here if you are still having issues and I am happy to reopen it!

**Closed by gforsyth** 2024-03-22 18:13 UTC
Labels: bug, bigquery

**Comment by kajen3** [comment] 2024-05-06 18:27
I have the same issue. `ibis==9.0.0`

```python
import ibis
import pandas as pd
project_id = "..."

df = pd.DataFrame(
    {
        "id": [1, 2],
        "product": ["a", "b"],
        "date": ["2021-01-01", "2021-01-02"],
        "target": [1.0, 2.0],
    }
)

con = ibis.connect(f"bigquery://{project_id}")
con.set_database(con.list_databases()[-2])
con.create_table(name="test_ibis", obj=df)
```

```
google.api_core.exceptions.BadRequest: 400 Syntax error: Missing whitespace between literal and alias at [1:46]; reason: invalidQuery, location: query, message: Syntax error: Missing whitespace between literal and alias at [1:46]
```

**Comment by cpcloud** [comment] 2024-05-06 18:37
@kajen3 I can't reproduce that with this:

```python
import ibis
import pandas as pd
project_id = "..."

df = pd.DataFrame(
    {
        "id": [1, 2],
        "product": ["a", "b"],
        "date": ["2021-01-01", "2021-01-02"],
        "target": [1.0, 2.0],
    }
)

con = ibis.connect(f"bigquery://{project_id}")
con.set_database(con.list_databases()[-2])
con.create_table(name="test_ibis", obj=df)
```

What version of sqlglot do you have installed?

**Comment by kajen3** [comment] 2024-05-06 19:09
@cpcloud  `sqlglot==23.11.2`

**Comment by cpcloud** [comment] 2024-05-06 20:28
Hm … possibly.

Can you share the query?

**Comment by kajen3** [comment] 2024-05-06 20:44
@cpcloud  How can I extract the query?

Running the following works just fine.
```python
con.raw_sql("""
create table `dev_test_dataset.test_ibis3` (
  store INTEGER,
  product STRING,
  date STRING,
  target FLOAT64);"""
)
con.raw_sql("INSERT INTO `dev_test_dataset.test_ibis` (store, product, date, target) VALUES (1, 'a', '2021-01-01', 1.0), (2, 'b', '2021-01-02', 2.0);" )
```

**Comment by kajen3** [comment] 2024-05-07 07:49
@cpcloud 
```
'CREATE TABLE ...-7b0a.dev_test_dataset.test_ibis5 AS SELECT\n  *\nFROM ...-7b0a._5c9e2c375ce6b104a24df800597ddbfd105e539c.`ibis_pandas_memtable_2dwueqn4hrdtrjpugfck6o3jhq`'
```

**Comment by HendrikHuel** [comment] 2024-05-07 11:17
After finding a related post on stackoverflow for bigquery I figured that some quotation marks are missing from the query.

To test it I did the following on

- python==3.11
- ibis==9.0.0
- sqlglot==23.12.2
- google-cloud-bigquery==3.21.0

1. I called `con.create_table` using the full table name quoted in "`" like so 
```
import ibis
import pandas as pd

df = pd.Dataframe()
con = ibis.bigquery.connect(project_id=<project_id>, dataset_id=<dataset_id>, location=<dataset_location))
con.create_table(name=f"`<project_id>.<dataset_id>.<table_name>`", obj=df, overwrite=True)
```
This injection puts the name of the created table in quotation marks "`".
2. I injected the following into `create_table` in the `ibis.backend.bigquery.__init__.py`
```
sql = stmt.sql(self.name)
sql = sql.split("FROM ")
sql = (sql[0] + "FROM " + f"`{sql[1]}`").replace("`ibis", "ibis").replace("``", "`")
```
This injection just puts the FROM table in quotation marks "`".

**Comment by gforsyth** [comment] 2024-05-07 13:41
I think I have a fix for this, just trying to find a failure case, first...

**Comment by gforsyth** [comment] 2024-05-07 15:35
@kajen3 and @HendrikHuel -- I've put up a fix in #9141.

Feel free to try out the fix there, but I was able to reproduce the 400 error and this fixed it on my end.

**Comment by kajen3** [comment] 2024-05-07 19:43
@gforsyth Thanks. I've tested it (`ibis==10.0.0.dev40`) with three tables, all in the same database. Two of them could be created without problems, the third raises the same error as before. The only difference is that the first two create the table from an `ibis.table` while the latter tries to create the table from a pandas DataFrame. 
From inspecting the query I suspect that the the backticks are missing for the first two parts of the source (the part after FROM).
```
'CREATE OR REPLACE TABLE `...-7b0a`.`dev_test_dataset`.`test_dataset_ibis` AS SELECT\n  *\nFROM ...-7b0a._5c9e2c375ce6b104a24df800597ddbfd105e539c.`ibis_pandas_memtable_wzrye6tpnvg2jhzyu5h34gfpcq`'
```

**Comment by gforsyth** [comment] 2024-05-07 21:09
ahh, gotcha, let me take a look.  thanks for testing this out, @kajen3 !

**Comment by gforsyth** [comment] 2024-05-07 21:29
hey @kajen3 -- I think I've got it sorted in #9149 if you want to take that for a spin!

**Comment by kajen3** [comment] 2024-05-08 10:02
@gforsyth No further error message. Thanks!
