### ISSUE TITLE
bug: invalid values returned by .first().over(w) or .last().over(w) when using the pandas backend

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#4676] opened 2022-10-19 10:07 UTC
Minimal reproducer:

```python
import ibis
import pandas as pd

df = pd.DataFrame(
    {

        "g": ["a", "a", "a", "a", "a"],
        "x": [0, 1, 2, 3, 4],
        "y": [3, 2, 0, 1, 1],
    }
)
df.to_parquet("test.parquet")
t_pandas = ibis.pandas.connect({"t": df}).table("t")
t_duckdb = ibis.duckdb.connect().register("test.parquet", table_name="t")


def simple_window_ops(t):
    w = ibis.window(
        group_by=t.g,
        order_by=[t.x, t.y],
        preceding=1,
        following=0,
    )
    return t.mutate(
        x_first=t.x.first().over(w),
        x_last=t.x.last().over(w),
        y_first=t.y.first().over(w),
        y_last=t.y.last().over(w),
    )
```

Then pandas does not seem to take the `preceding` and `following` window boundaries into account:

```python
>>> print(simple_window_ops(t_pandas).execute())
   g  x  y  x_first  x_last  y_first  y_last
0  a  0  3        0       4        3       1
1  a  1  2        0       4        3       1
2  a  2  0        0       4        3       1
3  a  3  1        0       4        3       1
4  a  4  1        0       4        3       1
```

while duckdb works as expected:

```python
>>> print(simple_window_ops(t_duckdb).execute())
   g  x  y  x_first  x_last  y_first  y_last
0  a  0  3        0       0        3       3
1  a  1  2        0       1        3       2
2  a  2  0        1       2        2       0
3  a  3  1        2       3        0       1
4  a  4  1        3       4        1       1
```

**Comment by ogrisel** [comment] 2022-10-19 10:10
Also, when I omit the `group_by` argument in the window spec:

```python
def simple_window_ops(t):
    w = ibis.window(
        # group_by=t.g,     # <-- commented out
        order_by=[t.x, t.y],
        preceding=1,
        following=0,
    )
    return t.mutate(
        x_first=t.x.first().over(w),
        x_last=t.x.last().over(w),
        y_first=t.y.first().over(w),
        y_last=t.y.last().over(w),
    )
```


then the pandas function fails with:

<details>

```python-traceback
Traceback (most recent call last):
  File "/Users/ogrisel/tmp/ibis_pandas_window.py", line 34, in <module>
    print(simple_window_ops(t_pandas).execute())
  File "/Users/ogrisel/code/ibis/ibis/expr/types/core.py", line 274, in execute
    return self._find_backend(use_default=True).execute(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/__init__.py", line 233, in execute
    return execute_and_reset(node, params=params, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 494, in execute_and_reset
    result = execute(
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 438, in main_execute
    return execute_with_scope(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 218, in execute_with_scope
    result = execute_until_in_scope(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 360, in execute_until_in_scope
    result = execute_node(
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/execution/selection.py", line 315, in execute_selection_dataframe
    result = build_df_from_projection(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/execution/selection.py", line 279, in build_df_from_projection
    data_pieces = [
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/execution/selection.py", line 280, in <listcomp>
    compute_projection(node, op, data, **kwargs) for node in selection_exprs
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/execution/selection.py", line 119, in compute_projection
    result = execute(node, scope=scope, timecontext=timecontext, **kwargs)
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 438, in main_execute
    return execute_with_scope(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 218, in execute_with_scope
    result = execute_until_in_scope(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 332, in execute_until_in_scope
    scopes = [
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 333, in <listcomp>
    execute_until_in_scope(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/core.py", line 360, in execute_until_in_scope
    result = execute_node(
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/execution/window.py", line 390, in execute_window_op
    result = post_process(
  File "/Users/ogrisel/code/ibis/ibis/backends/pandas/execution/window.py", line 89, in _post_process_order_by
    series = series.reorder_levels(names)
AttributeError: 'numpy.int64' object has no attribute 'reorder_levels'
```

</details>

while duckdb still works as expected.

**Comment by saulpw** [comment] 2022-10-19 20:45
Thanks for reporting this, @ogrisel.  This is definitely two bugs.  We'll try to get pandas to return valid results, or at the very least, raise a meaningful error if it can't.

**Comment by cpcloud** [comment] 2022-10-22 22:35
I don't think we can handle arbitrary window frame boundaries with pandas without a more generic interface to the rolling and expanding APIs that would allow us to definite exactly how to calculate the bounds.

**Comment by ogrisel** [comment] 2022-10-23 11:13
I think ibis should at least raise NotImplementedError in those cases instead of using pandas to compute erroneous results.

**Comment by ogrisel** [comment] 2022-10-23 11:15
Note that in this particular case, it would be possible to use pandas' `shift` method to get the correct results efficiently.

**Comment by cpcloud** [comment] 2022-11-07 21:59
The plan here is to prevent these kinds of computations from returning anything from the pandas backend. Fixing them is out of scope right now.

I think the failure case is caused by incorrect execution in the pandas backend when the following things are true:

1. `group_by` is set
2. `order_by` is set
3. `preceding` or `following` are not the defaults (perhaps `following` being 0 and and `preceding being the default may work)

**Comment by ogrisel** [comment] 2022-11-10 10:33
Indeed raising a `NotImplementedError` or similar would be fine. Maybe the error message could be extra helpful and state that the pandas backend does not support generic window operations but that some specific window operation via the `lag` and `lead`  methods.

**Comment by ogrisel** [comment] 2022-11-10 10:35
BTW, what about the second problem documented in https://github.com/ibis-project/ibis/issues/4676#issuecomment-1283756388

Do you want me to open a dedicated issue or both problems are likely to be solved by the same PR?

**Closed** 2023-01-02 09:49 UTC
Labels: bug, backends - pandas
