### ISSUE TITLE
bug(duckdb): columns with identical names but different case are considered duplicates

### ISSUE THREAD

**Issue by wleescor** [ibis-project/ibis#6946] opened 2023-08-28 02:54 UTC
### What happened?

using ibis.memtable on a pandas dataframe with duplicate columns (same column name, different case) give error
ValueError: schema column count does not match input data column count).

```
duplicate_columns = pd.DataFrame({'column': [1, 2, 3],
                                  'COLUMN': [4, 5, 6]})
ibis.memtable(duplicate_columns)
```

Ideally this can be fixed, or at least having clearer error message for these cases.

### What version of ibis are you using?

6.1.0

### What backend(s) are you using, if any?

duckdb

### Relevant log output

```sh
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File c:\repos\.venv\lib\site-packages\IPython\core\formatters.py:974, in MimeBundleFormatter.__call__(self, obj, include, exclude)
    971     method = get_real_method(obj, self.print_method)
    973     if method is not None:
--> 974         return method(include=include, exclude=exclude)
    975     return None
    976 else:

File c:\repos\.venv\lib\site-packages\ibis\expr\types\core.py:31, in _FixedTextJupyterMixin._repr_mimebundle_(self, *args, **kwargs)
     30 def _repr_mimebundle_(self, *args, **kwargs):
---> 31     bundle = super()._repr_mimebundle_(*args, **kwargs)
     32     bundle["text/plain"] = bundle["text/plain"].rstrip()
     33     return bundle

File c:\repos\.venv\lib\site-packages\rich\jupyter.py:48, in JupyterMixin._repr_mimebundle_(self, include, exclude, **kwargs)
     41 def _repr_mimebundle_(
     42     self: "ConsoleRenderable",
     43     include: Sequence[str],
     44     exclude: Sequence[str],
     45     **kwargs: Any,
     46 ) -> Dict[str, str]:
     47     console = get_console()
---> 48     segments = list(console.render(self, console.options))
     49     html = _render_segments(segments)
...
    109         )
    111     for (name, series), dtype in zip(df.items(), schema.types):
    112         df[name] = cls.convert_column(series, dtype)

ValueError: schema column count does not match input data column count
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment] 2023-08-28 10:12
@wleescor Thanks for the bug report and reproducible example!

I am able to reproduce and a fix should be in the next release (7.0.0).

**Comment by cpcloud** [comment] 2023-08-28 14:37
This problem turns out to be almost exclusively related to the way various backends handle case preservation.

Many of our SQL backends are unable to disambiguate selecting from a table that has column names that are identical up to but not including case.

Here's a non-exhaustive list of examples of this problem:

### DuckDB
```
D select * from (select 'a' as "col", 1 as "COL");
┌─────────┬───────┐
│   col   │ COL:1 │
│ varchar │ int32 │
├─────────┼───────┤
│ a       │     1 │
└─────────┴───────┘
```

### MSSQL
```
mssql@7b20aa29e856:/$ /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '1bis_Testing!' -Q "select * from (select 'a' as [col], 1 as [COL]) _"
Msg 8156, Level 16, State 1, Server 7b20aa29e856, Line 1
The column 'COL' was specified multiple times for '_'.
```

### MySQL
```
MariaDB ibis@localhost:ibis_testing> select * from (select 'a' as `col`, 1 as `COL`) _;
(1060, "Duplicate column name 'COL'")
```

### SQLite
```
sqlite> select * from (select 'a' as "col", 1 as "COL");
+-----+-------+
| col | COL:1 |
+-----+-------+
| a   | 1     |
+-----+-------+
```

### Trino

```
trino:default> select t0."col", t0."COL" from (values ('a', 1)) as t0 ("col", "COL");
Query 20230828_142829_07673_jdqzq failed: line 1:8: Column 't0.col' is ambiguous
select t0."col", t0."COL" from (values ('a', 1)) as t0 ("col", "COL")
```

**Comment by cpcloud** [comment] 2023-09-09 12:52
After diving into this, the situation here is unfortunately out of the control of ibis without ibis having to reimplement the quoting behavior of every backend to know when to raise an error.

Some backends handle mixed-case-equivalent identifiers just fine (ClickHouse, postgres) while many others do not (DuckDB, MSSQL, Trino). The ones that do not handle it well also are not consistent with each other in the way they behave. Some inject fake deduplicated column names while some raise a reasonable exception given the query.

DuckDB's behavior here is particularly difficult to deal with because there's no way to tell it to error on duplicate columns, though that's on the table as an option. See https://github.com/duckdb/duckdb/issues/8803 for discussion.

I don't think there's any action for us as ibis maintainers to take right now though, so I'm going to close the issue as unplanned.

**Closed by cpcloud** 2023-09-09 12:52 UTC
Labels: bug, duckdb
