### ISSUE TITLE
bug: regression reading JSON? not exactly sure

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6868] opened 2023-08-14 20:41 UTC
### What happened?

I don't have time to dig into this right now, so just logging what happened. I have an action running every 3 hours that was installing Ibis from master and running some stuff. It started failing yesterday: https://github.com/lostmygithubaccount/ibis-analytics/actions/runs/5848047279/job/15854924130

Simply downgrading to the release version of Ibis fixed, so I expect a regression? 

### What version of ibis are you using?

master

### What backend(s) are you using, if any?

DuckDB (seems to be the culprit), BigQuery

### Relevant log output

```sh
Traceback (most recent call last):
  File "/home/runner/work/ibis-analytics/ibis-analytics/transform.py", line 77, in <module>
    issues = clean_data(con.read_json("data/github/ibis-project/ibis/issues.*.json"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/duckdb/__init__.py", line 398, in read_json
    return self.table(table_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 622, in table
    sqla_table = self._get_sqla_table(name, schema=schema)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/duckdb/__init__.py", line 1004, in _get_sqla_table
    return super()._get_sqla_table(name, schema, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 512, in _get_sqla_table
    return self._handle_failed_column_type_inference(table, nulltype_cols)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 566, in _handle_failed_column_type_inference
    for colname, type in self._metadata(quoted_name):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/duckdb/__init__.py", line 951, in _metadata
    ibis_type = parse(type)
                ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/formats/parser.py", line 128, in parse
    return cls._get_type(sg.parse_one(text, into=DataType, read=cls.dialect))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/formats/parser.py", line 204, in _get_type
    return method(*parse_result.expressions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/formats/parser.py", line 145, in _get_STRUCT
    {field.name: cls._get_type(field.args["kind"]) for field in fields},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/formats/parser.py", line 145, in <dictcomp>
    {field.name: cls._get_type(field.args["kind"]) for field in fields},
                               ~~~~~~~~~~^^^^^^^^
KeyError: 'kind'
Command exited with non-zero status 1
2.29user 0.26system 0:02.69elapsed 94%CPU (0avgtext+0avgdata 215312maxresident)k
2056inputs+512outputs (7major+32229minor)pagefaults 0swaps
error: Recipe `run` failed on line 22 with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kszucs** [comment] 2023-08-16 18:15
@lostmygithubaccount could you please try to reproduce it with https://github.com/ibis-project/ibis/pull/6876 ?

**Comment by lostmygithubaccount** [comment] 2023-08-16 18:36
@kszucs gets farther along but fails still with a different issue:

```
INFO:root:processing stars...
INFO:root:processing issues...
Traceback (most recent call last):
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 144, in execute
    self.__c.execute(statement, parameters)
duckdb.BinderException: Binder Error: Could not find key "f1" in struct

Candidate Entries: "id", "url", "body", "title", "state"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cody/repos/ibis-analytics/transform.py", line 144, in <module>
    con.create_table("issues", issues, overwrite=True)
  File "/Users/cody/repos/ibis-analytics/ibis/ibis/backends/base/sql/alchemy/__init__.py", line 338, in create_table
    bind.execute(ctas)
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/cody/repos/ibis-analytics/venv/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 144, in execute
    self.__c.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (duckdb.BinderException) Binder Error: Could not find key "f1" in struct

Candidate Entries: "id", "url", "body", "title", "state"
[SQL: CREATE OR REPLACE TABLE issues AS WITH t0 AS
(SELECT t8.node AS node
FROM main._ibis_read_json_ikiwn7nrsrelxawcui2tinsghu AS t8),
t1 AS
(SELECT struct_extract(t0.node, 'title') AS title, struct_extract(t0.node, 'f1') AS f1, struct_extract(t0.node, 'id') AS id, struct_extract(t0.node, 'url') AS url, struct_extract(t0.node, 'labels') AS labels, struct_extract(t0.node, 'state') AS state, struct_extract(t0.node, 'stateReason') AS "stateReason", struct_extract(t0.node, 'closed') AS closed, struct_extract(t0.node, 'body') AS body, struct_extract(t0.node, 'comments') AS comments, struct_extract(t0.node, 'createdAt') AS "createdAt", struct_extract(t0.node, 'updatedAt') AS "updatedAt", struct_extract(t0.node, 'closedAt') AS "closedAt", struct_extract(t0.node, 'author') AS author
FROM t0),
t2 AS
(SELECT t1.title AS title, t1.f1 AS f1, t1.id AS id, t1.url AS url, t1.labels AS labels, t1.state AS state, t1."stateReason" AS "stateReason", t1.closed AS closed, t1.body AS body, t1.comments AS comments, t1."createdAt" AS "createdAt", t1."updatedAt" AS "updatedAt", t1."closedAt" AS "closedAt", struct_extract(t1.author, 'login') AS login
FROM t1),
t3 AS
(SELECT t2.title AS title, t2.f1 AS f1, t2.id AS id, t2.url AS url, t2.labels AS labels, t2.state AS state, t2."stateReason" AS state_reason, t2.closed AS closed, t2.body AS body, t2.comments AS comments, t2."createdAt" AS created_at, t2."updatedAt" AS updated_at, t2."closedAt" AS closed_at, t2.login AS login
FROM t2),
t4 AS
(SELECT t3.title AS title, t3.f1 AS f1, t3.id AS id, t3.url AS url, t3.labels AS labels, t3.state AS state, t3.state_reason AS state_reason, t3.closed AS closed, t3.body AS body, t3.comments AS comments, CAST(t3.created_at AS TIMESTAMP WITH TIME ZONE) AS created_at, CAST(t3.updated_at AS TIMESTAMP WITH TIME ZONE) AS updated_at, CAST(t3.closed_at AS TIMESTAMP WITH TIME ZONE) AS closed_at, t3.login AS login
FROM t3),
t5 AS
(SELECT t4.title AS title, t4.f1 AS f1, t4.id AS id, t4.url AS url, t4.labels AS labels, t4.state AS state, t4.state_reason AS state_reason, t4.closed AS closed, t4.body AS body, t4.comments AS comments, t4.created_at AS created_at, t4.updated_at AS updated_at, t4.closed_at AS closed_at, t4.login AS login
FROM t4 ORDER BY t4.created_at DESC),
t6 AS
(SELECT t5.title AS title, t5.f1 AS f1, t5.id AS id, t5.url AS url, t5.labels AS labels, t5.state AS state, t5.state_reason AS state_reason, t5.closed AS closed, t5.body AS body, t5.comments AS comments, t5.created_at AS created_at, t5.updated_at AS updated_at, t5.closed_at AS closed_at, t5.login AS login, t5.closed_at IS NOT NULL AS is_closed
FROM t5)
 SELECT t7.title, t7.f1, t7.id, t7.url, t7.labels, CASE WHEN t7.is_closed THEN 'closed' ELSE 'open' END AS state, t7.state_reason, t7.closed, t7.body, t7.comments, t7.created_at, t7.updated_at, t7.closed_at, t7.login, t7.is_closed, t7.total_issues
FROM (SELECT t6.title AS title, t6.f1 AS f1, t6.id AS id, t6.url AS url, t6.labels AS labels, t6.state AS state, t6.state_reason AS state_reason, t6.closed AS closed, t6.body AS body, t6.comments AS comments, t6.created_at AS created_at, t6.updated_at AS updated_at, t6.closed_at AS closed_at, t6.login AS login, t6.is_closed AS is_closed, count(*) OVER (ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS total_issues
FROM t6) AS t7]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by kszucs** [comment] 2023-08-16 19:19
Thanks, going to take a look!

**Comment by cpcloud** [comment] 2023-08-17 06:30
This is caused by a bug in sqlglot parsing:

```
In [9]: import sqlglot as sg

In [10]: sg.parse_one("struct(number bigint)", read="duckdb", into=sg.exp.DataType)
Out[10]:
(DATATYPE this: Type.STRUCT, expressions:
  (DATATYPE this: Type.DECIMAL, expressions:
    (DATATYPESIZE this:
      (LITERAL this: 18, is_string: False)),
    (DATATYPESIZE this:
      (LITERAL this: 3, is_string: False)), nested: False, prefix: False), nested: True, prefix: False)
```

Note the `DECIMAL` type, which I suspect is stemming from `number` being a valid type.

**Comment by cpcloud** [comment] 2023-08-17 06:34
Open an issue upstream: https://github.com/tobymao/sqlglot/issues/2080

**Comment by cpcloud** [comment] 2023-09-09 12:56
This was fixed by https://github.com/tobymao/sqlglot/issues/2080 and a subsequent upgrade of ibis sqlglot lower bound to `17.15.0`.

**Closed by cpcloud** 2023-09-09 12:56 UTC
Labels: bug, dependencies, requires upstream support
