### ISSUE TITLE
[Question] How could I create Array Aggregate SQLs?

### ISSUE THREAD

**Issue by marianyfs** [ibis-project/ibis#2881] opened 2021-07-27 20:44 UTC
```
SELECT 
     column_a,
     ARRAY_AGG(column_b ORDER BY column_e DESC LIMIT 1)[SAFE_OFFSET(0)] as column_b,
FROM dataset_name.table_name
GROUP BY 1
```
OR
```
      SELECT
            column_a,
            SUM(column_b) AS column_b
        FROM (
            SELECT DISTINCT
              column_a,
              column_b
            FROM (
              SELECT 
                column_a,
                FIRST_VALUE(column_b)
                  OVER (
                    PARTITION BY column_a, column_d
                    ORDER BY column_e DESC
                  ) AS column_b
              FROM dataset_name.table_name
            )
        )
      GROUP BY 1
```

ibis-bigquery==0.1.1
ibis-framework==1.4.0

**Comment by datapythonista** [comment] 2021-07-29 20:54
Sorry for the delay @marianyfs. If this is a bigquery specific question, you may want to open the question in https://github.com/ibis-project/ibis-bigquery/issues.

Not sure if it's implemented in bigquery, but `ARRAY_AGG` is translated in PostgreSQL and other backends to the ibis `table.column.collect()`.

**Comment by marianyfs** [comment] 2021-07-30 22:03
My difficulty in this query is related to the parameters inside the ARRAY AGG: (column_b ORDER BY column_e DESC LIMIT 1) and the operation to get the first value [SAFE_OFFSET(0)].

I don't think it's a BigQuery-only question, so I created the question here. Other backends have the same (or equivalent) operations

**Comment by cpcloud** [comment] 2021-12-16 13:52
This is definitely something we want to implement in the near future. Duplicate of #2929.

**Closed by cpcloud** 2021-12-16 13:52 UTC
