### ISSUE TITLE
feat: quantile support for postgres/redshift

### ISSUE THREAD

**Issue by FedericoV** [ibis-project/ibis#1365] opened 2018-02-23 21:56 UTC
Hi,

Currently, attempting to use the .quantile() command while using the postgres driver gives this error:

```
~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+76.g5952b1a-py3.5.egg/ibis/sql/compiler.py in translate(self, expr)
   1162         else:
   1163             raise com.OperationNotDefinedError(
-> 1164                 'No translation rule for {}'.format(type(op))
   1165             )
   1166 

OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.Quantile'>
```

Any chance this could be added in a future release?

**Comment by FedericoV** [comment] 2018-02-23 23:25
I'm taking a stab at implementing this following: http://docs.ibis-project.org/notebooks/tutorial/9-Adding-a-new-expression.html but I'm running into a few errors.

If any core devs are available for some pointers, I'm happy to work on this myself.

**Comment by kszucs** [comment] 2018-02-23 23:40
Hey @FedericoV ! What kind of errors are You running into?

**Comment by FedericoV** [comment] 2018-02-23 23:48
I first tried to familiarize myself a bit with the postgres back end, and tried this:

```
import sqlalchemy as sa
import ibis.expr.datatypes as dt
from ibis.expr.types import DecimalValue, DecimalColumn, NumericValue, DecimalValue


from ibis.expr import rules
from ibis.expr.operations import ValueOp, Reduction, _coerce_integer_to_double_type

def _mean_output_type(self):
    arg = self.args[0]
    if isinstance(arg, DecimalValue):
        t = dt.Decimal(arg.meta.precision, 38)
    elif isinstance(arg, NumericValue):
        t = 'double'
    else:
        raise NotImplementedError
    return t

class Dumb_Mean(Reduction):    
    output_type = rules.scalar_output(_mean_output_type)

def dumb_mean(array_value):
    return Dumb_Mean(array_value).to_expr()

DecimalColumn.dumb_mean = dumb_mean

@ibis.postgres.compiles(Dumb_Mean)
def compile_approx_quantile(translator, expr):
    # pull out the arguments to the expression

    # compile the argument
    arg, = expr.op().args

    # return a SQLAlchemy expression that calls into the PostgreSQL
    return sa.func.encode(sa.func.digest(arg, 'dumb_mean'), 'avg')
```

And if I apply it, I get this:

```
avg_price.dumb_mean().execute()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-772b689ccf83> in <module>()
----> 1 avg_price.dumb_mean().execute()

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/expr/types.py in execute(self, limit, async, params, **kwargs)
    190         """
    191         from ibis.client import execute
--> 192         return execute(self, limit=limit, async=async, params=params, **kwargs)
    193 
    194     def compile(self, limit=None, params=None):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(expr, limit, async, params, **kwargs)
    329     backend, = validate_backends(list(find_backends(expr)))
    330     return backend.execute(expr, limit=limit, async=async, params=params,
--> 331                            **kwargs)
    332 
    333 

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(self, expr, params, limit, async, **kwargs)
    226             raise NotImplementedError
    227         else:
--> 228             return self._execute_query(ast.queries[0], async=async, **kwargs)
    229 
    230     def _execute_query(self, ddl, async=False, **kwargs):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in _execute_query(self, ddl, async, **kwargs)
    230     def _execute_query(self, ddl, async=False, **kwargs):
    231         klass = self.async_query if async else self.sync_query
--> 232         inst = klass(self, ddl, **kwargs)
    233         return inst.execute()
    234 

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in __init__(self, client, ddl, **kwargs)
     45 
     46         if isinstance(ddl, comp.DDL):
---> 47             self.compiled_ddl = ddl.compile()
     48         else:
     49             self.compiled_ddl = ddl

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/sql/alchemy.py in compile(self)
   1024 
   1025         for step in steps:
-> 1026             frag = step(frag)
   1027 
   1028         return frag

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/sql/alchemy.py in _add_select(self, table_set)
   1051         for expr in self.select_set:
   1052             if isinstance(expr, ir.ValueExpr):
-> 1053                 arg = self._translate(expr, named=True)
   1054             elif isinstance(expr, ir.TableExpr):
   1055                 if expr.equals(self.table_set):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/sql/compiler.py in _translate(self, expr, named, permit_subquery)
   1347                                      named=named,
   1348                                      permit_subquery=permit_subquery)
-> 1349         return translator.get_result()
   1350 
   1351     def equals(self, other, cache=None):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/sql/compiler.py in get_result(self)
   1120         Build compiled SQL expression from the bottom up and return as a string
   1121         """
-> 1122         translated = self.translate(self.expr)
   1123         if self._needs_name(self.expr):
   1124             # TODO: this could fail in various ways

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/sql/compiler.py in translate(self, expr)
   1159         elif type(op) in self._registry:
   1160             formatter = self._registry[type(op)]
-> 1161             return formatter(self, expr)
   1162         else:
   1163             raise com.OperationNotDefinedError(

<ipython-input-3-c4c753f9ced2> in compile_approx_quantile(translator, expr)
     31 
     32     # compile the argument
---> 33     arg, = expr.op().args
     34 
     35     # return a SQLAlchemy expression that calls into the PostgreSQL

ValueError: too many values to unpack (expected 1)
```

**Comment by FedericoV** [comment] 2018-02-23 23:50
If I do the logical thing and remove the comma (since it's only unpacking a single argument) I get this other error instead:
```
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1192                         parameters,
-> 1193                         context)
   1194         except BaseException as e:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    506     def do_execute(self, cursor, statement, parameters, context=None):
--> 507         cursor.execute(statement, parameters)
    508 

ProgrammingError: can't adapt type 'DecimalColumn'

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
<ipython-input-10-772b689ccf83> in <module>()
----> 1 avg_price.dumb_mean().execute()

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/expr/types.py in execute(self, limit, async, params, **kwargs)
    190         """
    191         from ibis.client import execute
--> 192         return execute(self, limit=limit, async=async, params=params, **kwargs)
    193 
    194     def compile(self, limit=None, params=None):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(expr, limit, async, params, **kwargs)
    329     backend, = validate_backends(list(find_backends(expr)))
    330     return backend.execute(expr, limit=limit, async=async, params=params,
--> 331                            **kwargs)
    332 
    333 

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(self, expr, params, limit, async, **kwargs)
    226             raise NotImplementedError
    227         else:
--> 228             return self._execute_query(ast.queries[0], async=async, **kwargs)
    229 
    230     def _execute_query(self, ddl, async=False, **kwargs):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in _execute_query(self, ddl, async, **kwargs)
    231         klass = self.async_query if async else self.sync_query
    232         inst = klass(self, ddl, **kwargs)
--> 233         return inst.execute()
    234 
    235     def compile(self, expr, params=None, limit=None):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(self)
     54     def execute(self):
     55         # synchronous by default
---> 56         with self.client._execute(self.compiled_ddl, results=True) as cur:
     57             result = self._fetch(cur)
     58 

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/sql/alchemy.py in _execute(self, query, results)
    982     def _execute(self, query, results=True):
    983         with self.begin() as con:
--> 984             return AlchemyProxy(con.execute(query))
    985 
    986     @invalidates_reflection_cache

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in execute(self, object, *multiparams, **params)
    946             raise exc.ObjectNotExecutableError(object)
    947         else:
--> 948             return meth(self, multiparams, params)
    949 
    950     def _execute_function(self, func, multiparams, params):

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/sql/elements.py in _execute_on_connection(self, connection, multiparams, params)
    267     def _execute_on_connection(self, connection, multiparams, params):
    268         if self.supports_execution:
--> 269             return connection._execute_clauseelement(self, multiparams, params)
    270         else:
    271             raise exc.ObjectNotExecutableError(self)

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_clauseelement(self, elem, multiparams, params)
   1058             compiled_sql,
   1059             distilled_params,
-> 1060             compiled_sql, distilled_params
   1061         )
   1062         if self._has_events or self.engine._has_events:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1198                 parameters,
   1199                 cursor,
-> 1200                 context)
   1201 
   1202         if self._has_events or self.engine._has_events:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1411                 util.raise_from_cause(
   1412                     sqlalchemy_exception,
-> 1413                     exc_info
   1414                 )
   1415             else:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py in raise_from_cause(exception, exc_info)
    201     exc_type, exc_value, exc_tb = exc_info
    202     cause = exc_value if exc_value is not exception else None
--> 203     reraise(type(exception), exception, tb=exc_tb, cause=cause)
    204 
    205 if py3k:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    184             value.__cause__ = cause
    185         if value.__traceback__ is not tb:
--> 186             raise value.with_traceback(tb)
    187         raise value
    188 

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1191                         statement,
   1192                         parameters,
-> 1193                         context)
   1194         except BaseException as e:
   1195             self._handle_dbapi_exception(

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    505 
    506     def do_execute(self, cursor, statement, parameters, context=None):
--> 507         cursor.execute(statement, parameters)
    508 
    509     def do_execute_no_params(self, cursor, statement, context=None):
```
ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'DecimalColumn' [SQL: 'SELECT encode(digest(%(digest_1)s, %(digest_2)s), %(encode_1)s) AS tmp \nFROM fba_pricing.fee_imp_xch_mm AS t0']

**Comment by kszucs** [comment] 2018-02-23 23:58
Could You please print `avg_price.dumb_mean()`?

**Comment by FedericoV** [comment] 2018-02-24 00:02
```
print (avg_price.dumb_mean())

ref_0
PostgreSQLTable[table]
  name: fee_imp_xch_mm
  schema:
    marketplace_id : int32
....


Dumb_Mean[decimal(38, 38)]
  avg_our_price = Column[decimal(38, 8)*] 'avg_our_price' from table
    ref_0
  where:
    None
```

**Comment by kszucs** [comment] 2018-02-24 00:04
The issue is probably the input signature defined [here](https://github.com/ibis-project/ibis/blob/master/ibis/expr/operations.py#L659). So the length of `expr.op().args` will be two, first the argument You're expected, and second the optional where condition passed [here](https://github.com/ibis-project/ibis/blob/master/ibis/expr/api.py#L548).

Would You try the following in `compile_approx_quantile`: `arg, where = expr.op().args`?

**Comment by FedericoV** [comment] 2018-02-24 01:02
Nice catch.  I tried that, and I still get this error:

```
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1192                         parameters,
-> 1193                         context)
   1194         except BaseException as e:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    506     def do_execute(self, cursor, statement, parameters, context=None):
--> 507         cursor.execute(statement, parameters)
    508 

ProgrammingError: can't adapt type 'DecimalColumn'

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
<ipython-input-8-772b689ccf83> in <module>()
----> 1 avg_price.dumb_mean().execute()

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/expr/types.py in execute(self, limit, async, params, **kwargs)
    190         """
    191         from ibis.client import execute
--> 192         return execute(self, limit=limit, async=async, params=params, **kwargs)
    193 
    194     def compile(self, limit=None, params=None):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(expr, limit, async, params, **kwargs)
    329     backend, = validate_backends(list(find_backends(expr)))
    330     return backend.execute(expr, limit=limit, async=async, params=params,
--> 331                            **kwargs)
    332 
    333 

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(self, expr, params, limit, async, **kwargs)
    226             raise NotImplementedError
    227         else:
--> 228             return self._execute_query(ast.queries[0], async=async, **kwargs)
    229 
    230     def _execute_query(self, ddl, async=False, **kwargs):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in _execute_query(self, ddl, async, **kwargs)
    231         klass = self.async_query if async else self.sync_query
    232         inst = klass(self, ddl, **kwargs)
--> 233         return inst.execute()
    234 
    235     def compile(self, expr, params=None, limit=None):

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/client.py in execute(self)
     54     def execute(self):
     55         # synchronous by default
---> 56         with self.client._execute(self.compiled_ddl, results=True) as cur:
     57             result = self._fetch(cur)
     58 

~/src/anaconda3/lib/python3.5/site-packages/ibis_framework-0.12.0+77.g25ca530-py3.5.egg/ibis/sql/alchemy.py in _execute(self, query, results)
    982     def _execute(self, query, results=True):
    983         with self.begin() as con:
--> 984             return AlchemyProxy(con.execute(query))
    985 
    986     @invalidates_reflection_cache

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in execute(self, object, *multiparams, **params)
    946             raise exc.ObjectNotExecutableError(object)
    947         else:
--> 948             return meth(self, multiparams, params)
    949 
    950     def _execute_function(self, func, multiparams, params):

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/sql/elements.py in _execute_on_connection(self, connection, multiparams, params)
    267     def _execute_on_connection(self, connection, multiparams, params):
    268         if self.supports_execution:
--> 269             return connection._execute_clauseelement(self, multiparams, params)
    270         else:
    271             raise exc.ObjectNotExecutableError(self)

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_clauseelement(self, elem, multiparams, params)
   1058             compiled_sql,
   1059             distilled_params,
-> 1060             compiled_sql, distilled_params
   1061         )
   1062         if self._has_events or self.engine._has_events:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1198                 parameters,
   1199                 cursor,
-> 1200                 context)
   1201 
   1202         if self._has_events or self.engine._has_events:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1411                 util.raise_from_cause(
   1412                     sqlalchemy_exception,
-> 1413                     exc_info
   1414                 )
   1415             else:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py in raise_from_cause(exception, exc_info)
    201     exc_type, exc_value, exc_tb = exc_info
    202     cause = exc_value if exc_value is not exception else None
--> 203     reraise(type(exception), exception, tb=exc_tb, cause=cause)
    204 
    205 if py3k:

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    184             value.__cause__ = cause
    185         if value.__traceback__ is not tb:
--> 186             raise value.with_traceback(tb)
    187         raise value
    188 

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1191                         statement,
   1192                         parameters,
-> 1193                         context)
   1194         except BaseException as e:
   1195             self._handle_dbapi_exception(

~/src/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    505 
    506     def do_execute(self, cursor, statement, parameters, context=None):
--> 507         cursor.execute(statement, parameters)
    508 
    509     def do_execute_no_params(self, cursor, statement, context=None):

ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'DecimalColumn' [SQL: 'SELECT encode(digest(%(digest_1)s, %(digest_2)s), %(encode_1)s) AS tmp \nFROM fba_pricing.fee_imp_xch_mm AS t0'] [parameters: {'digest_2': 'dumb_mean', 'encode_1': 'avg', 'digest_1': ref_0
PostgreSQLTable[table]
  name: fee_imp_xch_mm
  schema:
    marketplace_id : int32
    asin : string
    weekend_day : date
    merchant_custome ... (1296 characters truncated) ... mal(38, 8)
    max_sales_price_retail : decimal(38, 8)
    is_cee : string

avg_our_price = Column[decimal(38, 8)*] 'avg_our_price' from table
  ref_0}] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by cpcloud** [comment] 2018-02-24 02:07
You have to call translate on arg

**Comment by cpcloud** [comment] 2018-02-24 02:09
Your function also doesn't reduce, so it will fail with a strange error from sqlalchemy most likely

**Comment by cpcloud** [comment] 2018-02-24 02:18
If what I said doesn't make sense let me know and I can elaborate.

**Comment by FedericoV** [comment] 2018-02-24 08:58
I have a vague intuition of what you are saying (average is an operation that maps an array to a scalar) but I'm not very sure about how that's expressed in the function.  I tried digging into the codebase a bit, but I couldn't find many stand alone implementations of reduce functions for the SQL back end.

**Comment by FedericoV** [comment] 2018-02-24 09:00
I also wanted to get around to exposing to IBIS the approx percentile function, which involves mapping an array of reals to an array of categorical values - I just thought starting with mean would be easier :)

**Comment by cpcloud** [comment] 2018-02-26 14:15
@FedericoV can you go to the ibis gitter chat: https://gitter.im/ibis-dev/Lobby

**Comment by cpcloud** [comment] 2018-02-26 14:18
Here's what I mean by the `translate on arg` comment:

Your code:

```python
DecimalColumn.dumb_mean = dumb_mean

@ibis.postgres.compiles(Dumb_Mean)
def compile_approx_quantile(translator, expr):
    # pull out the arguments to the expression

    # compile the argument
    arg, = expr.op().args

    # return a SQLAlchemy expression that calls into the PostgreSQL
    return sa.func.encode(sa.func.digest(arg, 'dumb_mean'), 'avg')
```

does not call `translator.translate(arg)`. That's why you're seeing an error message with the ibis expression as a bound parameter.

Change your code to include that call. You may still get errors because `encode`/`decode` probably do not work on numbers.

**Comment by cpcloud** [comment] 2022-07-06 18:19
Closed by https://github.com/ibis-project/ibis/pull/4000.

**Closed by cpcloud** 2022-07-06 18:19 UTC
Labels: feature
