### ISSUE TITLE
Investigate ibis import time

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2544] opened 2020-11-25 20:30 UTC
Recently on newer pythons `test_import_time` has been taking slightly longer than the 2 second delta. 

https://github.com/ibis-project/ibis/runs/1452081748?check_suite_focus=true

**Comment by datapythonista** [comment] 2020-11-26 10:58
There is a comment in that test that says it shouldn't be tested in the CI because it's not reliable, and it skips it on Azure. It's failing now because we moved the testing to GitHub Actions, and that skip wasn't updated.

But I don't think loading in more than 2 seconds is acceptable, even in windows in the CI. I think this is caused by loading too many backends. I hope this is fixed in #2379, when backends are loaded in a lazy way. It should be merged soon.

**Comment by datapythonista** [comment] 2020-11-26 10:59
@gerrymanoim if you are interested, you can remove the unused skip, and feel free to check if there is any other that is skiping in azure.

**Comment by datapythonista** [comment] 2020-11-26 11:03
Closing as duplicate of #2520

**Closed by datapythonista** 2020-11-26 11:03 UTC
Labels: ci, performance, testing
