### ISSUE TITLE
bug(postgres): `last` function doesn't support int or float columns

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#8793] opened 2024-03-27 13:01 UTC
### What happened?

Trying to do a `distinct on keep last` with the postgres backend fails (log output below).

We can probably do a better job of erroring cleanly if there isn't an obvious workaround.

reproducer:

```python
[ins] In [1]: import ibis

[ins] In [2]: con = ibis.postgres.connect(
         ...:     user="postgres",
         ...:     password="postgres",
         ...:     host="0.0.0.0",
         ...:     port=5432,
         ...:     database="ibis_testing",
         ...: )

[ins] In [3]: ibis.set_backend(con)

[ins] In [4]: t = ibis.examples.agriculture.fetch()

[nav] In [5]: expr = t.distinct(on=["x"], keep="last")

[ins] In [6]: expr.to_pyarrow()
```

This also fails on 8.0.0

### What version of ibis are you using?

main @ 36237885d

### What backend(s) are you using, if any?

postgres

### Relevant log output

```sh
---------------------------------------------------------------------------
UndefinedFunction                         Traceback (most recent call last)
Cell In[6], line 1
----> 1 expr.to_pyarrow()

File ~/github.com/ibis-project/ibis/ibis/expr/types/core.py:452, in Expr.to_pyarrow(self, params, limit, **kwargs)
    424 @experimental
    425 def to_pyarrow(
    426     self,
   (...)
    430     **kwargs: Any,
    431 ) -> pa.Table:
    432     """Execute expression and return results in as a pyarrow table.
    433 
    434     This method is eager and will execute the associated expression
   (...)
    450         A pyarrow table holding the results of the executed expression.
    451     """
--> 452     return self._find_backend(use_default=True).to_pyarrow(
    453         self, params=params, limit=limit, **kwargs
    454     )

File ~/github.com/ibis-project/ibis/ibis/backends/__init__.py:221, in _FileIOHandler.to_pyarrow(self, expr, params, limit, **kwargs)
    217 arrow_schema = schema.to_pyarrow()
    218 with self.to_pyarrow_batches(
    219     table_expr, params=params, limit=limit, **kwargs
    220 ) as reader:
--> 221     table = pa.Table.from_batches(reader, schema=arrow_schema)
    223 return expr.__pyarrow_result__(
    224     table.rename_columns(table_expr.columns).cast(arrow_schema)
    225 )

File /nix/store/xglf45k8zzyfsk3a18c0f8j3kv77gkh7-python3-3.12.2-env/lib/python3.12/site-packages/pyarrow/table.pxi:4104, in pyarrow.lib.Table.from_batches()

File /nix/store/xglf45k8zzyfsk3a18c0f8j3kv77gkh7-python3-3.12.2-env/lib/python3.12/site-packages/pyarrow/ipc.pxi:666, in pyarrow.lib.RecordBatchReader.__next__()

File /nix/store/xglf45k8zzyfsk3a18c0f8j3kv77gkh7-python3-3.12.2-env/lib/python3.12/site-packages/pyarrow/ipc.pxi:700, in pyarrow.lib.RecordBatchReader.read_next_batch()

File /nix/store/xglf45k8zzyfsk3a18c0f8j3kv77gkh7-python3-3.12.2-env/lib/python3.12/site-packages/pyarrow/error.pxi:88, in pyarrow.lib.check_status()

File ~/github.com/ibis-project/ibis/ibis/backends/sql/__init__.py:374, in <genexpr>(.0)
    372 schema = expr.as_table().schema()
    373 array_type = schema.as_struct().to_pyarrow()
--> 374 arrays = (
    375     pa.array(map(tuple, batch), type=array_type)
    376     for batch in self._cursor_batches(
    377         expr, params=params, limit=limit, chunk_size=chunk_size
    378     )
    379 )
    380 batches = map(pa.RecordBatch.from_struct_array, arrays)
    382 return pa.ipc.RecordBatchReader.from_batches(schema.to_pyarrow(), batches)

File ~/github.com/ibis-project/ibis/ibis/backends/sql/__init__.py:331, in SQLBackend._cursor_batches(self, expr, params, limit, chunk_size)
    322 def _cursor_batches(
    323     self,
    324     expr: ir.Expr,
   (...)
    327     chunk_size: int = 1 << 20,
    328 ) -> Iterable[list]:
    329     self._run_pre_execute_hooks(expr)
--> 331     with self._safe_raw_sql(
    332         self.compile(expr, limit=limit, params=params)
    333     ) as cursor:
    334         while batch := cursor.fetchmany(chunk_size):
    335             yield batch

File /nix/store/7yh2ax34jd7fgf17mjfd3c6niw1h2hsj-python3-3.12.2/lib/python3.12/contextlib.py:137, in _GeneratorContextManager.__enter__(self)
    135 del self.args, self.kwds, self.func
    136 try:
--> 137     return next(self.gen)
    138 except StopIteration:
    139     raise RuntimeError("generator didn't yield") from None

File ~/github.com/ibis-project/ibis/ibis/backends/postgres/__init__.py:763, in Backend._safe_raw_sql(self, *args, **kwargs)
    761 @contextlib.contextmanager
    762 def _safe_raw_sql(self, *args, **kwargs):
--> 763     with contextlib.closing(self.raw_sql(*args, **kwargs)) as result:
    764         yield result

File ~/github.com/ibis-project/ibis/ibis/backends/postgres/__init__.py:789, in Backend.raw_sql(self, query, **kwargs)
    786     raise
    788 try:
--> 789     cursor.execute(query, **kwargs)
    790 except Exception:
    791     con.rollback()

UndefinedFunction: function last(double precision) does not exist
LINE 1: SELECT "t0"."x", LAST("t0"."y") AS "y" FROM "agriculture" AS...
                         ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment] 2024-08-10 13:02
The issue about types is a red herring. That's the same error you get when the function simply doesn't exist, which is almost certainly the case here. Postgres doesn't have builtin `first`/`last` functions, but we define them in `postgres.sql` for testing purposes.

The reason I did that was because there are a number of extensions that implement these functions and call them `first` and `last`, so it seemed to make sense at the time to roll our own and test against that.

Closing as not a bug in Ibis.

**Closed by cpcloud** 2024-08-10 13:02 UTC
Labels: bug, postgres
