### ISSUE TITLE
feat(duckdb): support the ability to load multiple files in a single command

### ISSUE THREAD

**Issue by p-a-a-a-trick** [ibis-project/ibis#4204] opened 2022-07-07 15:30 UTC
Request: allow registering multiple tables using glob when connecting to the duckdb backend using `ibis.connect('duckdb://...`

`conn = ibis.connect('duckdb://farmers.csv')` will only give me one table, `farmers`.

To connect to multiple CSVs using one DuckDB connection via the `ibis.connect` function, I instead use `:memory:` and do the following:

```python
conn = ibis.connect('duckdb://:memory:')

files = glob.glob('farm_data/*.csv')
for file in files:
    fname = 'csv://' + file
    tname = file.replace('farm_data/', '').replace('.csv', '')
    conn.register(fname, tname)
```
Ideally we'd get something like this instead:

```python
conn = ibis.connect('duckdb://farm_data/*.csv')
```

**Comment by cpcloud** [comment] 2023-01-30 15:24
This issue is a duplicate of https://github.com/ibis-project/ibis/issues/4906 and has been fixed!

**Closed by cpcloud** 2023-01-30 15:24 UTC
Labels: feature, ux, backends
