### ISSUE TITLE
'invalid snapshot identifier' when using `read_postgres()` with DuckDB backend

### ISSUE THREAD

**Issue by iangow** [ibis-project/ibis#8319] opened 2024-02-12 19:00 UTC
### What happened?

I am seeing the issue described here with Ibis. It seems that DuckDB requires uses of `libpq` connection strings in place of URIs. Perhaps it makes sense to keep URIs in Ibis and translate behind the scenes. 

https://github.com/duckdb/postgres_scanner/issues/154

### What version of ibis are you using?

8.0.0

### What backend(s) are you using, if any?

DuckDB and PostgreSQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment] 2024-02-12 21:11
Thanks for the report!

If it's not a huge burden would you mind pasting a reproducible example of what's failing?

**Comment by iangow** [comment] 2024-02-12 21:14
Reproducibility is tricky because of the PostgreSQL angle. Have you seen any examples in issues here before? (For example, one using a public server.) I could perhaps adapt one of those.

**Comment by cpcloud** [comment] 2024-02-12 21:20
As long as you can show some SQL and some Ibis I think I can handle a workable postgres instance.

**Comment by gforsyth** [comment] 2024-02-12 21:22
I can't reproduce this locally -- can you show the schema of the postgres table you're trying to attach to?

```
[ins] In [16]: con.read_postgres("postgres://postgres:postgres@0.0.0.0:5432/ibis_testing", "batting")
Out[16]: 
DatabaseTable: batting
  playerID string
  yearID   int64
  stint    int64
  teamID   string
  lgID     string
  G        int64
  AB       int64
  R        int64
  H        int64
  X2B      int64
  X3B      int64
  HR       int64
  RBI      int64
  SB       int64
  CS       int64
  BB       int64
  SO       int64
  IBB      int64
  HBP      int64
  SH       int64
  SF       int64
  GIDP     int64
```

**Comment by iangow** [comment] 2024-02-12 22:11
Let me work on this. I'm not seeing the issue in my reprex either.

**Comment by cpcloud** [comment] 2024-02-23 18:25
Closing this out! Please open again if you're able to reproduce.

**Closed by cpcloud** 2024-02-23 18:25 UTC
Labels: bug, postgres, duckdb
