### ISSUE TITLE
CI: Undo pytest<6.0.0rc1 pin when higher version works with CI

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2278] opened 2020-07-13 20:21 UTC
`pytest` is pinned to be <=6.0.0rc1 in #2277 to fix the CI (see #2275)

We should unpin when higher versions of pyarrow work with the CI

**Comment by datapythonista** [comment] 2020-07-14 09:38
Is this a duplicate of #2222 or #2192?

**Comment by timothydijamco** [comment] 2020-07-14 10:57
Oops, this is for `pytest` not `pyarrow`

**Comment by cpcloud** [comment] 2021-11-23 12:52
This is fixed. We're now using `^6` (`>=6,<7`) in CI.

**Closed by cpcloud** 2021-11-23 12:52 UTC
Labels: ci
