### ISSUE TITLE
duckdb: some parquet files don't load

### ISSUE THREAD

**Issue by saulpw** [ibis-project/ibis#4294] opened 2022-07-29 20:32 UTC
This code:

```
import ibis

con = ibis.duckdb.connect()
con.register('part-0.parquet')
```

produces this error:

```Traceback (most recent call last):
  File "/home/saul/data/t.py", line 6, in <module>
    con.register('part-0.parquet')
  File "/home/saul/.local/lib/python3.10/site-packages/ibis/backends/duckdb/__init__.py", line 148, in register
    return self.table(table_name)
  File "/home/saul/.local/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 412, in table
    sqla_table = self._get_sqla_table(
  File "/home/saul/.local/lib/python3.10/site-packages/ibis/backends/duckdb/__init__.py", line 186, in _get_sqla_table
    table = super()._get_sqla_table(name, schema, **kwargs)
  File "/home/saul/.local/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 367, in _get_sqla_table
    return sa.Table(name, self.meta, schema=schema, autoload=autoload)
  File "<string>", line 2, in __new__
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 615, in __new__
    with util.safe_reraise():
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 611, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 686, in _init
    self._autoload(
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 721, in _autoload
    conn_insp.reflect_table(
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3850, in get_columns
    column_info = self._get_column_info(
  File "/home/saul/.local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3887, in _get_column_info
    attype = re.sub(r"\(.*\)", "", format_type)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

~~Renaming the file to `part_0.parquet` causes it to load fine.~~  Actually not.

**Comment by gforsyth** [comment] 2022-07-29 20:43
suspect this may have to do with parquet files that have arrays in them

**Comment by cpcloud** [comment] 2022-07-30 10:48
What's the schema of `part-0.parquet`?

Playing around with some array data and exporting to parquet, things seem to work:

1. Create some data using the DuckDB CLI:

```
D create table t (id int primary key, a int[], b text[], c struct(a int, b text, c double[][])[]);
D insert into t select id, [1] as a, ['a'] as b, [struct_pack(a := 1, b := 'a', c := [[1.0, 2.0], [3.0, 4.0]])] as c from generate_series(1, 5) as _(id);
D table t;
┌────┬─────┬─────┬───────────────────────────────────────────────────────────────────────┐
│ id │  a  │  b  │                                   c                                   │
├────┼─────┼─────┼───────────────────────────────────────────────────────────────────────┤
│ 1  │ [1] │ [a] │ [{'a': 1, 'b': a, 'c': [[1.000000, 2.000000], [3.000000, 4.000000]]}] │
│ 2  │ [1] │ [a] │ [{'a': 1, 'b': a, 'c': [[1.000000, 2.000000], [3.000000, 4.000000]]}] │
│ 3  │ [1] │ [a] │ [{'a': 1, 'b': a, 'c': [[1.000000, 2.000000], [3.000000, 4.000000]]}] │
│ 4  │ [1] │ [a] │ [{'a': 1, 'b': a, 'c': [[1.000000, 2.000000], [3.000000, 4.000000]]}] │
│ 5  │ [1] │ [a] │ [{'a': 1, 'b': a, 'c': [[1.000000, 2.000000], [3.000000, 4.000000]]}] │
└────┴─────┴─────┴───────────────────────────────────────────────────────────────────────┘
```

2. Export it to parquet

```
D export database 'pq' (format parquet);
```

3. Register with ibis in IPython

```
In [1]: import ibis

In [2]: con = ibis.duckdb.connect()

In [3]: t = con.register("pq/t.parquet")

In [4]: t
Out[4]:
AlchemyTable: t
  id int32
  a  array<int32>
  b  array<string>
  c  array<struct<a: int32, b: string, c: array<float64>>>
```

**Comment by cpcloud** [comment] 2022-08-02 18:33
@saulpw I was able to look into this and with current ibis
10a659d66145403c872ec176b8a739613f0061e7 I cannot reproduce the problem.

Here's an IPython session that shows registering the table and
repr-ing in interactive mode.

```
In [38]: import ibis

In [39]: con = ibis.duckdb.connect()

In [40]: t = con.register("part-0.parquet")

In [41]: ibis.options.interactive = True

In [42]: t
Out[42]:
      anon_ticket_number      issue_datetime state  anon_plate_id  division  ...  fine issuing_agency   gps zip_code                                 geometry
0                8984775 2017-12-02 19:11:00    NJ        4731693       NaN  ...  51.0            PPA  True  19107.0   [486793.8962446982, 4422797.865182051]
1                8984776 2017-12-02 19:00:00    PA        4731694       NaN  ...  76.0            PPA  True  19107.0   [486605.1045470014, 4422055.784661669]
2                8984777 2017-12-01 18:55:00    DC        4731695       NaN  ...  51.0            PPA  True  19127.0   [481174.4046948851, 4430435.410799652]
3                8984778 2017-10-01 20:18:00    PA        4731696       NaN  ...  41.0         POLICE   NaN      NaN                               [nan, nan]
4                8984779 2017-10-11 21:30:00    PA        4731697       NaN  ...  36.0            PPA  True  19103.0  [485097.1136233578, 4422362.0298382975]
...                  ...                 ...   ...            ...       ...  ...   ...            ...   ...      ...                                      ...
9995             7697070 2017-02-16 10:31:00    NJ        2004801       NaN  ...  26.0            PPA  True  19104.0   [482357.9785371379, 4422607.172461129]
9996             7697071 2017-02-17 10:40:00    NJ        2004801       NaN  ...  26.0            PPA  True  19104.0    [482362.9286568391, 4422605.38516325]
9997             7697072 2017-02-20 10:38:00    NJ        2004801       NaN  ...  26.0            PPA  True  19104.0   [482355.2521073819, 4422610.175503747]
9998             7697073 2017-02-22 10:58:00    NJ        2004801       NaN  ...  26.0            PPA  True  19104.0  [482361.2164482082, 4422603.7242755825]
9999             7697074 2017-03-11 11:17:00    PA        2051950       NaN  ...  36.0            PPA  True  19103.0    [484663.668156383, 4422097.069169454]

[10000 rows x 12 columns]
```

I wonder if this is an environment issue.

Can you show the output of `pip freeze` with the interpreter/environment you
used to run the example?

**Comment by cpcloud** [comment] 2022-08-03 10:53
@saulpw I'm going to close this out for now! Happy to help figure out the issue, but I don't think this is a problem in ibis.

**Closed by cpcloud** 2022-08-03 10:53 UTC
Labels: bug, backends - duckdb
