### ISSUE TITLE
feature request : Updating and Deleting data in a row

### ISSUE THREAD

**Issue by cocoaway** [ibis-project/ibis#3750] opened 2022-04-10 09:14 UTC
I think being able to delete data from a table is just as useful as creating and inserting them.

The same for updating it.

I would like to propose to create:

Delete entire record/row
 `connection.delete ('table_name', idx)` where idx is the table index.

Update columns values in a record/row
 `connection.update ('table_name', idx, data_to_be_updated as dict )` where idx is the table index followed by a dict with new data.

Thx.

**Comment by saulpw** [comment] 2022-04-11 09:23
Hi @cocoaway, thanks for the suggestion.  General DDL support for backends is already on the roadmap (#2796), and there's been interest in DDL/update previously (#2123).  The API will probably take an expression as a "where" clause, instead of a table index (by which I think you mean "row number"?) as it's more generally supportable.  We're hoping to get to this in the next few months.

Closing this as a duplicate of #2796.

**Closed by saulpw** 2022-04-11 09:23 UTC
