### ISSUE TITLE
bug: using concat gives `IbisError: incorrect number of args`

### ISSUE THREAD

**Issue by xnmp** [ibis-project/ibis#4448] opened 2022-08-31 08:55 UTC
Minimal example:

```
import ibis

pop = ibis.table(
    [
        ('name', 'string'),
        ('country', 'string'),
        ('gender', 'string'),
        ('age', 'int16'),
    ],
    name='population',
)
pp = pop.mutate(kk = lambda x: x['country'].concat(';'))
ibis.impala.compile(pp)
```

This gives `IbisError: incorrect number of args`

**Comment by cpcloud** [comment] 2022-08-31 09:48
@xnmp Thanks for the bug report!

What version of ibis are you running? I cannot reproduce this issue when running against `master`:

```
In [3]: import ibis

In [4]: pop = ibis.table(
   ...:     [
   ...:         ('name', 'string'),
   ...:         ('country', 'string'),
   ...:         ('gender', 'string'),
   ...:         ('age', 'int16'),
   ...:     ],
   ...:     name='population',
   ...: )
   ...:

In [5]: pp = pop.mutate(kk = lambda x: x['country'].concat(';'))

In [6]: res = ibis.impala.compile(pp)

In [7]: print(res)
SELECT *, concat(`country`, ';') AS `kk`
FROM population
```

We're cutting a release in about a week, so stay tuned for the fix!

**Comment by xnmp** [comment] 2022-09-01 00:52
@cpcloud Thanks for responding so quickly! I'm using Ibis 3.1. 

Also I got it working by going into `ibis/backends/base/sql/registry/main.py`, where there's a dictionary called `operation_registry`, and changing the value for `ops.StringConcat` to `varargs('concat')`.

**Comment by cpcloud** [comment] 2022-09-01 08:49
@xnmp Thanks! I'll close this out then. Watch out for 3.2 in the next week or so.

**Closed by cpcloud** 2022-09-01 08:49 UTC
Labels: bug, backends - impala, question
