### ISSUE TITLE
bug: Error: cannot start a transaction within a transaction when using raw_sql against duckdb

### ISSUE THREAD

**Issue by amoeba** [ibis-project/ibis#6999] opened 2023-09-01 00:30 UTC
### What happened?

I ran this code:

```
import ibis

con = ibis.duckdb.connect() 
con.raw_sql("SET memory_limit='1GB';")
con.raw_sql("SELECT current_setting('memory_limit');")
```

and got this error:

> sqlalchemy.exc.OperationalError: (duckdb.TransactionException) TransactionContext Error: cannot start a transaction within a transaction

<details>
<summary>Full output</summary>

```
Traceback (most recent call last):
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1095, in _begin_impl
    self.engine.dialect.do_begin(self.connection)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 246, in do_begin
    connection.execute("begin")
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 142, in execute
    self.__c.execute(statement)
duckdb.TransactionException: TransactionContext Error: cannot start a transaction within a transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bryce/tmp/ibis-duckdb.py", line 5, in <module>
    con.raw_sql("SELECT current_setting('memory_limit');")
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 574, in raw_sql
    return self.con.connect().execute(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1834, in _execute_context
    self._autobegin()
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 781, in _autobegin
    self.begin()
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 849, in begin
    self._transaction = RootTransaction(self)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2667, in __init__
    self._connection_begin_impl()
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2685, in _connection_begin_impl
    self.connection._begin_impl(self)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1097, in _begin_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1095, in _begin_impl
    self.engine.dialect.do_begin(self.connection)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 246, in do_begin
    connection.execute("begin")
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 142, in execute
    self.__c.execute(statement)
sqlalchemy.exc.OperationalError: (duckdb.TransactionException) TransactionContext Error: cannot start a transaction within a transaction
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
</details>

I then ran what I felt like was analogous code directly in DuckDB and it worked as expected:

```
❯ duckdb
v0.6.1 919cad22e8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET memory_limit='1GB';
D SELECT current_setting('memory_limit');
┌─────────────────────────────────┐
│ current_setting('memory_limit') │
│             varchar             │
├─────────────────────────────────┤
│ 1.0GB                           │
└─────────────────────────────────┘
```

### What version of ibis are you using?

6.2.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment] 2023-09-01 00:39
your version of DuckDB is relatively old (6.1 vs 8.1 as the latest), can you try upgrading that? I don't see this error on Ibis's master branch and DuckDB 0.8.1

```python
[ins] In [1]: import ibis

[ins] In [2]: ibis.__version__
Out[2]: '6.1.0'

[ins] In [3]: import duckdb

[ins] In [4]: duckdb.__version__
Out[4]: '0.8.1'

[ins] In [5]: import ibis
         ...:
         ...: con = ibis.duckdb.connect()
         ...: con.raw_sql("SET memory_limit='1GB';")
         ...: con.raw_sql("SELECT current_setting('memory_lim
         ...: it');")
Out[5]: <sqlalchemy.engine.cursor.LegacyCursorResult at 0x169112e10>
```

**Comment by cboettig** [comment] 2023-09-01 00:48
I see this too, on 

```
duckdb==0.8.1
duckdb-engine==0.9.2
ibis-framework==6.2.0
```

**Comment by lostmygithubaccount** [comment] 2023-09-01 00:53
I am able to reproduce this in one virtual environment

**Comment by lostmygithubaccount** [comment] 2023-09-01 01:01
well you can downgrade SQLAlchemy to fix this:

```python
Successfully installed SQLAlchemy-2.0.20
(venv) cody@dkdcvoda ibis % ipy
Python 3.11.4 (main, Jul 31 2023, 11:45:21) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: import ibis
         ...:
         ...: con = ibis.duckdb.connect()
         ...: con.raw_sql("SET memory_limit='1GB';")
         ...: con.raw_sql("SELECT current_setting('memory_lim
         ...: it');")
-------------------------------------------------------------
TransactionException        Traceback (most recent call last)
File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1095, in Connection._begin_impl(self, transaction)
   1094 try:
-> 1095     self.engine.dialect.do_begin(self.connection)
   1096 except BaseException as e:

File ~/repos/ibis/venv/lib/python3.11/site-packages/duckdb_engine/__init__.py:246, in Dialect.do_begin(self, connection)
    245 def do_begin(self, connection: "Connection") -> None:
--> 246     connection.execute("begin")

File ~/repos/ibis/venv/lib/python3.11/site-packages/duckdb_engine/__init__.py:142, in ConnectionWrapper.execute(self, statement, parameters, context)
    141 elif parameters is None:
--> 142     self.__c.execute(statement)
    143 else:

TransactionException: TransactionContext Error: cannot start a transaction within a transaction

The above exception was the direct cause of the following exception:

OperationalError            Traceback (most recent call last)
Cell In[1], line 5
      3 con = ibis.duckdb.connect()
      4 con.raw_sql("SET memory_limit='1GB';")
----> 5 con.raw_sql("SELECT current_setting('memory_limit');")

File ~/repos/ibis/ibis/backends/base/sql/alchemy/__init__.py:584, in BaseAlchemyBackend.raw_sql(self, query)
    583 def raw_sql(self, query):
--> 584     return self.con.connect().execute(
    585         sa.text(query) if isinstance(query, str) else query
    586     )

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1412, in Connection.execute(self, statement, parameters, execution_options)
   1410     raise exc.ObjectNotExecutableError(statement) from err
   1411 else:
-> 1412     return meth(
   1413         self,
   1414         distilled_parameters,
   1415         execution_options or NO_OPTIONS,
   1416     )

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:515, in ClauseElement._execute_on_connection(self, connection, distilled_params, execution_options)
    513     if TYPE_CHECKING:
    514         assert isinstance(self, Executable)
--> 515     return connection._execute_clauseelement(
    516         self, distilled_params, execution_options
    517     )
    518 else:
    519     raise exc.ObjectNotExecutableError(self)

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1635, in Connection._execute_clauseelement(self, elem, distilled_parameters, execution_options)
   1623 compiled_cache: Optional[CompiledCacheType] = execution_options.get(
   1624     "compiled_cache", self.engine._compiled_cache
   1625 )
   1627 compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
   1628     dialect=dialect,
   1629     compiled_cache=compiled_cache,
   (...)
   1633     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1634 )
-> 1635 ret = self._execute_context(
   1636     dialect,
   1637     dialect.execution_ctx_cls._init_compiled,
   1638     compiled_sql,
   1639     distilled_parameters,
   1640     execution_options,
   1641     compiled_sql,
   1642     distilled_parameters,
   1643     elem,
   1644     extracted_params,
   1645     cache_hit=cache_hit,
   1646 )
   1647 if has_events:
   1648     self.dispatch.after_execute(
   1649         self,
   1650         elem,
   (...)
   1654         ret,
   1655     )

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1834, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1831     TransactionalContext._trans_ctx_check(self)
   1833 if self._transaction is None:
-> 1834     self._autobegin()
   1836 context.pre_exec()
   1838 if context.execute_style is ExecuteStyle.INSERTMANYVALUES:

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:781, in Connection._autobegin(self)
    779 def _autobegin(self) -> None:
    780     if self._allow_autobegin and not self.__in_begin:
--> 781         self.begin()

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:849, in Connection.begin(self)
    784 """Begin a transaction prior to autobegin occurring.
    785
    786 E.g.::
   (...)
    846
    847 """
    848 if self._transaction is None:
--> 849     self._transaction = RootTransaction(self)
    850     return self._transaction
    851 else:

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2667, in RootTransaction.__init__(self, connection)
   2665     TransactionalContext._trans_ctx_check(connection)
   2666 self.connection = connection
-> 2667 self._connection_begin_impl()
   2668 connection._transaction = self
   2670 self.is_active = True

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2685, in RootTransaction._connection_begin_impl(self)
   2684 def _connection_begin_impl(self) -> None:
-> 2685     self.connection._begin_impl(self)

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1097, in Connection._begin_impl(self, transaction)
   1095     self.engine.dialect.do_begin(self.connection)
   1096 except BaseException as e:
-> 1097     self._handle_dbapi_exception(e, None, None, None, None)
   1098 finally:
   1099     self.__in_begin = False

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2339, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context, is_sub_exec)
   2337 elif should_wrap:
   2338     assert sqlalchemy_exception is not None
-> 2339     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
   2340 else:
   2341     assert exc_info[1] is not None

File ~/repos/ibis/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1095, in Connection._begin_impl(self, transaction)
   1092     self.dispatch.begin(self)
   1094 try:
-> 1095     self.engine.dialect.do_begin(self.connection)
   1096 except BaseException as e:
   1097     self._handle_dbapi_exception(e, None, None, None, None)

File ~/repos/ibis/venv/lib/python3.11/site-packages/duckdb_engine/__init__.py:246, in Dialect.do_begin(self, connection)
    245 def do_begin(self, connection: "Connection") -> None:
--> 246     connection.execute("begin")

File ~/repos/ibis/venv/lib/python3.11/site-packages/duckdb_engine/__init__.py:142, in ConnectionWrapper.execute(self, statement, parameters, context)
    140     self.__c.register(view_name, df)
    141 elif parameters is None:
--> 142     self.__c.execute(statement)
    143 else:
    144     self.__c.execute(statement, parameters)

OperationalError: (duckdb.TransactionException) TransactionContext Error: cannot start a transaction within a transaction
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[ins] In [2]: exit
(venv) cody@dkdcvoda ibis % pip install 'SQLAlchemy==1.4.49'
Collecting SQLAlchemy==1.4.49
  Obtaining dependency information for SQLAlchemy==1.4.49 from https://files.pythonhosted.org/packages/47/3d/de827556bafdc40a4db10a5beccaee31d1840871ce867a372e7a37bf7c95/SQLAlchemy-1.4.49-cp311-cp311-macosx_10_9_universal2.whl.metadata
  Using cached SQLAlchemy-1.4.49-cp311-cp311-macosx_10_9_universal2.whl.metadata (10 kB)
Using cached SQLAlchemy-1.4.49-cp311-cp311-macosx_10_9_universal2.whl (1.6 MB)
Installing collected packages: SQLAlchemy
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 2.0.20
    Uninstalling SQLAlchemy-2.0.20:
      Successfully uninstalled SQLAlchemy-2.0.20
Successfully installed SQLAlchemy-1.4.49
(venv) cody@dkdcvoda ibis % ipy
Python 3.11.4 (main, Jul 31 2023, 11:45:21) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: import ibis
         ...:
         ...: con = ibis.duckdb.connect()
         ...: con.raw_sql("SET memory_limit='1GB';")
         ...: con.raw_sql("SELECT current_setting('memory_lim
         ...: it');")
Out[1]: <sqlalchemy.engine.cursor.LegacyCursorResult at 0x12d992850>


```

**Comment by amoeba** [comment] 2023-09-01 01:15
Thanks for the help @lostmygithubaccount. That does seem to fix the issue here.

**Comment by amoeba** [comment] 2023-09-01 20:05
I wanted to close the loop here. Would it make sense to make a change of some sort here?

**Comment by lostmygithubaccount** [comment] 2023-09-01 20:14
yes, downgrading SQLAlchemy is far from an ideal workaround. will bring this up in a triage meeting sometime if it's not covered by someone from the notifications

**Comment by amoeba** [comment] 2023-09-01 20:14
Great, thanks @lostmygithubaccount.

**Comment by cpcloud** [comment] 2023-09-07 18:07
This is documented in our docstrings for the `raw_sql` method (that was removed in the quarto-ification, but will be back soon).

The reason this is happening is because you're creating a transaction inside of another, because you haven't called `close()` on the resulting cursor.

I will close this issue once we add back the `Backend` API docs.

**Closed** 2023-09-08 16:56 UTC
Labels: bug
